Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-03, with the labels that each got.

#2100 Added some Swedish translations
  src/Resources/translations/EasyAdminBundle.sv.xlf
Labels: feature, finished

#2104 Method call uses 3 parameters, but method signature uses 2 parameters
  src/EventListener/ExceptionListener.php
Labels: finished

#2105 Access modifiers shall be defined
  src/EasyAdminBundle.php
  src/Event/EasyAdminEvents.php
  src/Search/Finder.php
  src/Search/Paginator.php
Labels: finished

#2106 Remove form delete_empty legacy BC
  src/Form/Type/Configurator/CollectionTypeConfigurator.php
Labels: finished

#2107 Short syntax for applied operation
  src/Exception/ExceptionContext.php
Labels: finished

#2108 Nested ternary operator should not be used.
  src/EventListener/ExceptionListener.php
Labels: finished

#2109 Remove unused method
  src/Twig/EasyAdminTwigExtension.php
Labels: finished

#2118 Use new Twig namespace
  src/Twig/EasyAdminTwigExtension.php
Labels: finished

#2119 Unnecessary call arguments specification
  src/DataCollector/EasyAdminDataCollector.php
  src/EventListener/ExceptionListener.php
Labels: finished

#2120 Fix typehint doc
  src/Search/QueryBuilder.php
Labels: finished

#2114 Using fully-qualified function calls is faster
  src/Configuration/ConfigManager.php
  src/Configuration/NormalizerConfigPass.php
  src/Controller/AdminController.php
  src/DataCollector/EasyAdminDataCollector.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EasyAdminExtension.php
  src/EventListener/ControllerListener.php
  src/Exception/FlattenException.php
  src/Form/EventListener/EasyAdminAutocompleteSubscriber.php
  src/Form/EventListener/EasyAdminTabSubscriber.php
  src/Form/Type/Configurator/AutocompleteTypeConfigurator.php
  src/Form/Type/Configurator/CheckboxTypeConfigurator.php
  src/Form/Type/Configurator/CollectionTypeConfigurator.php
  src/Form/Type/Configurator/EntityTypeConfigurator.php
  src/Form/Type/Configurator/IvoryCKEditorTypeConfigurator.php
  src/Form/Type/EasyAdminFormType.php
  src/Router/EasyAdminRouter.php
  src/Search/QueryBuilder.php
  src/Twig/EasyAdminTwigExtension.php
Labels: finished

#2113 'in_array(...)' misused
  src/Configuration/NormalizerConfigPass.php
Labels: finished

#2116 'empty(...)' usage
  src/Search/QueryBuilder.php
Labels: finished

#2123 Always use mb_substr() and use PHP 7.1 negative offsets for strings
  src/Configuration/ActionConfigPass.php
  src/Configuration/DesignConfigPass.php
  src/Configuration/NormalizerConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Configuration/TemplateConfigPass.php
  src/Configuration/ViewConfigPass.php
  src/DependencyInjection/Configuration.php
  src/Exception/ExceptionContext.php
Labels: finished

#2124 Improved the use of list()
  src/Form/Guesser/MissingDoctrineOrmTypeGuesser.php
  src/Search/QueryBuilder.php
Labels: finished

#2139 Trigger a proper deprecaton notice when using the deprecated route name
  src/Controller/AdminController.php
Labels: finished

#2147 Removed more deprecated methods
  src/Controller/AdminController.php
  tests/Controller/CustomEntityControllerTest.php
  tests/Fixtures/App/config/config_custom_entity_controller.yml
  tests/Fixtures/AppTestBundle/Admin/CustomCategoryController.php
  tests/Fixtures/AppTestBundle/Admin/CustomController.php
Labels: finished

#2152 Fix VichUploaderBundle example
  doc/integration/vichuploaderbundle.rst
Labels: bug, doc

#2155 Added tests and tweaked the new redirection logic
  src/Controller/AdminController.php
  tests/Controller/DisabledActionsTest.php
  tests/Fixtures/App/config/config_disabled_actions.yml
Labels: finished

#2160 Fixed code syntax to make tests green again
  src/Controller/AdminController.php
  tests/Controller/DisabledActionsTest.php
Labels: finished

#2171 Minor tweaks to translation files
  src/Resources/translations/EasyAdminBundle.el.xlf
  src/Resources/translations/EasyAdminBundle.fa.xlf
  src/Resources/translations/messages.el.xlf
  src/Resources/translations/messages.fa.xlf
  src/Resources/translations/messages.fi.xlf
  src/Resources/translations/messages.lt.xlf
Labels: finished

#2175 Defined a default typography for the h1, h2, h3, ... headings
  src/Resources/views/css/easyadmin.css.twig
Labels: bug, finished

#2168 Allow to translate flash messages
  src/Resources/views/default/flash_messages.html.twig
Labels: bug, finished

#2174 Use the HTML <time> element to display date and time related properties
  src/Resources/views/default/field_date.html.twig
  src/Resources/views/default/field_datetime.html.twig
  src/Resources/views/default/field_datetimetz.html.twig
  src/Resources/views/default/field_time.html.twig
Labels: feature, finished

#2180 [Doc] fixed some issues in the VichUploader integration tutorial
  doc/integration/vichuploaderbundle.rst
Labels: bug, doc, finished

#2188 Add german translation for impersonate logout
  src/Resources/translations/EasyAdminBundle.de.xlf
Labels: finished
