Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-12, with the labels that each got.

#2460 Applied PHP-CS-Fixer and enabled the "native_function_invocation" rule
  .php_cs
  src/Configuration/ActionConfigPass.php
  src/Configuration/ConfigManager.php
  src/Configuration/DefaultConfigPass.php
  src/Configuration/DesignConfigPass.php
  src/Configuration/MenuConfigPass.php
  src/Configuration/MetadataConfigPass.php
  src/Configuration/NormalizerConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Configuration/TemplateConfigPass.php
  src/Configuration/ViewConfigPass.php
  src/Controller/AdminController.php
  src/DataCollector/EasyAdminDataCollector.php
  src/DependencyInjection/Compiler/EasyAdminFormTypePass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/EasyAdminExtension.php
  src/EventListener/ControllerListener.php
  src/EventListener/RequestPostInitializeListener.php
  src/Exception/EntityNotFoundException.php
  src/Exception/EntityRemoveException.php
  src/Exception/FlattenException.php
  src/Exception/ForbiddenActionException.php
  src/Exception/UndefinedEntityException.php
  src/Form/EventListener/EasyAdminTabSubscriber.php
  src/Form/Type/Configurator/FOSCKEditorTypeConfigurator.php
  src/Form/Type/Configurator/TextareaTypeConfigurator.php
  src/Form/Type/Configurator/TypeConfigurator.php
  src/Form/Type/EasyAdminAutocompleteType.php
  src/Form/Type/EasyAdminFormType.php
  src/Form/Util/FormTypeHelper.php
  src/Router/EasyAdminRouter.php
  src/Search/Autocomplete.php
  src/Search/QueryBuilder.php
  src/Twig/EasyAdminTwigExtension.php
  tests/Configuration/ConfigManagerTest.php
  tests/Controller/AdvancedFormLayoutTest.php
  tests/Controller/AutocompleteTest.php
  tests/Controller/CustomMenuTest.php
  tests/Controller/CustomTranslationDomainTest.php
  tests/Controller/CustomizedBackendTest.php
  tests/Controller/DefaultBackendTest.php
  tests/Controller/DisabledActionsTest.php
  tests/Controller/EmptyActionLabelsTest.php
  tests/Controller/FormViewTest.php
  tests/Controller/InternationalizationTest.php
  tests/Controller/OverrideEasyAdminControllerTest.php
  tests/Controller/SplitConfigurationTest.php
  tests/Fixtures/AbstractTestCase.php
  tests/Fixtures/App/DynamicConfigLoadingKernel.php
  tests/Fixtures/AppTestBundle/Admin/CustomCategoryControllerAsService.php
  tests/Fixtures/AppTestBundle/DataFixtures/AppFixtures.php
  tests/Fixtures/AppTestBundle/Entity/FunctionalTests/Purchase.php
  tests/Form/Type/EasyAdminAutocompleteTypeTest.php
  tests/Router/EasyAdminRouterTest.php
  tests/Search/AutocompleteTest.php
  tests/bootstrap.php
Labels: finished

#2469 Updated the exception listener
  assets/css/easyadmin-theme/errors.scss
  src/EventListener/ExceptionListener.php
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/exception.html.twig
Labels: finished

#2470 Minor improvement in the exception listener
  src/EventListener/ExceptionListener.php
  src/Resources/views/default/exception.html.twig
Labels: finished

#2473 Use Form Type classes everywhere
  src/Controller/AdminController.php
  src/Form/EventListener/EasyAdminAutocompleteSubscriber.php
  tests/Form/Type/EasyAdminAutocompleteTypeTest.php
Labels: finished

#2481 Don't make ConfigPassInterface final
  src/Configuration/ConfigPassInterface.php
Labels: finished

#2482 Fixed a config issue
  src/DependencyInjection/Configuration.php
Labels: bug

#2485 PHP >= 5.3.0 compatibility in TemplateConfigPass
  src/Configuration/TemplateConfigPass.php
Labels: bug

#2494 Added an UPGRADE guide to 2.x version
  UPGRADE-2.0.md
Labels: finished

#2502 Add missing french translation
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: finished

#2499 Do not restrict select2 to #main
  src/Resources/views/default/includes/_select2_widget.html.twig
Labels: feature, finished

#2505 Limit the image width when using an image as the logo
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: bug, finished

#2504 Apply datagrid hover on th
  assets/css/easyadmin-theme/datagrids.scss
Labels: finished

#2509 Resolve missing controller deprecations
  src/Controller/AdminController.php
  tests/Fixtures/App/config/routing_base.yml
  tests/Fixtures/App/config/routing_custom_menu.php
  tests/Fixtures/App/config/routing_override_controller.yml
Labels: finished

#2508 Resolve transchoice deprecation warning
  src/Resources/config/services.xml
  src/Twig/EasyAdminTwigExtension.php
Labels: feature, finished

#2512 Fixed the use of HTML in help messages
  src/Resources/views/default/layout.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Fixtures/App/config/config_customized_backend.yml
Labels: bug, finished

#2513 Use the same button size classes as Bootstrap 4
  assets/css/easyadmin-theme/buttons.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#2521 Improved the design of the "no results" search page
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: finished

#2532 Always show the footer pagination
  src/Resources/views/default/paginator.html.twig
Labels: feature, finished

#2535 fix PHP 5.3 compatibility
  .travis.yml
  src/Controller/AdminController.php
Labels: bug, finished

#2544 Fixed UPGRADE-2.0.md about AdminController
  UPGRADE-2.0.md
Labels: doc, finished

#2542 Updated the docs for Symfony 4
  doc/integration/vichuploaderbundle.rst
Labels: bug, doc, finished

#2545 Mention the Rector PHP set in the UPGRADE guide
  UPGRADE-2.0.md
Labels: doc, finished
