Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-10, with the labels that each got.

#2374 Add default field for percent type. Fixes #2208.
  src/Configuration/TemplateConfigPass.php
  src/Resources/views/default/field_percent.html.twig
Labels: feature

#2378 Added some notes about routing and annotations
  doc/book/complex-dynamic-backends.rst
  doc/book/installation.rst
Labels: doc, finished

#2379 Fixed the order of update events in AJAX edits
  src/Controller/AdminController.php
Labels: bug, finished

#2380 Improved the vich_image_widget template
  src/Resources/views/form/bootstrap_3_layout.html.twig
Labels: bug, finished

#2383 Added an option to customize the CSS class of menu items
  doc/book/menu-configuration.rst
  src/Configuration/MenuConfigPass.php
  src/Resources/views/default/menu.html.twig
  tests/Controller/CustomMenuTest.php
  tests/Fixtures/App/config/config_custom_menu.yml
Labels: feature

#2388 Updated the docs for Symfony 4 + Flex + EasyAdmin 2.x
  doc/book/actions-configuration.rst
  doc/book/basic-configuration.rst
  doc/book/complex-dynamic-backends.rst
  doc/book/design-configuration.rst
  doc/book/edit-new-configuration.rst
  doc/book/installation.rst
  doc/book/list-search-show-configuration.rst
  doc/book/menu-configuration.rst
  doc/book/your-first-backend.rst
  doc/index.rst
  doc/integration/fosrestbundle.rst
  doc/integration/fosuserbundle.rst
  doc/integration/ivoryckeditorbundle.rst
  doc/integration/vichuploaderbundle.rst
  doc/tutorials/complex-backend-config.rst
  doc/tutorials/custom-actions.rst
  doc/tutorials/custom-property-options.rst
  doc/tutorials/i18n.rst
  doc/tutorials/tips-and-tricks.rst
Labels: doc, finished

#2389 Removed some deprecated features
  src/Configuration/TemplateConfigPass.php
  src/Controller/AdminController.php
  src/DataCollector/EasyAdminDataCollector.php
  src/DependencyInjection/Configuration.php
  tests/Configuration/ConfigManagerTest.php
  tests/Configuration/fixtures/deprecations/input/admin_003.yml
  tests/Configuration/fixtures/deprecations/input/admin_004.yml
  tests/Configuration/fixtures/deprecations/input/admin_005.yml
  tests/Configuration/fixtures/deprecations/input/admin_006.yml
  tests/Configuration/fixtures/deprecations/input/admin_007.yml
  tests/Configuration/fixtures/deprecations/input/admin_008.yml
  tests/Configuration/fixtures/deprecations/input/admin_009.yml
  tests/Configuration/fixtures/deprecations/input/admin_010.yml
  tests/Configuration/fixtures/deprecations/input/admin_011.yml
  tests/Configuration/fixtures/deprecations/input/admin_012.yml
  tests/Configuration/fixtures/deprecations/output/config_003.yml
  tests/Configuration/fixtures/deprecations/output/config_004.yml
  tests/Configuration/fixtures/deprecations/output/config_005.yml
  tests/Configuration/fixtures/deprecations/output/config_006.yml
  tests/Configuration/fixtures/deprecations/output/config_007.yml
  tests/Configuration/fixtures/deprecations/output/config_008.yml
  tests/Configuration/fixtures/deprecations/output/config_009.yml
  tests/Configuration/fixtures/deprecations/output/config_010.yml
  tests/Configuration/fixtures/deprecations/output/config_011.yml
  tests/Configuration/fixtures/deprecations/output/config_012.yml
Labels: finished

#2390 Require Symfony 4.1
  composer.json
Labels: finished
