Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-06, with the labels that each got.

#2235 Allow line break from translation in help message
  src/Resources/views/default/layout.html.twig
Labels: feature, finished

#2226 fixed tabs translations
  src/Resources/views/form/bootstrap_3_layout.html.twig
Labels: bug, finished

#2249 save a lot of template exists checks
  composer.json
  src/Configuration/TemplateConfigPass.php
Labels: feature, finished

#2258 Fixed code syntax to make tests green again
  src/Cache/CacheManager.php
Labels: finished

#2259 [Bugfix] Depend on router instead of router.default
  src/Resources/config/services.xml
Labels: bug, finished
