Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-02, with the labels that each got.

#2037 Fix form attribute collision in theme
  src/Resources/views/form/bootstrap_3_layout.html.twig
Labels: bug, confirmed, finished

#2046 Revert delete form
  src/Resources/views/default/includes/_delete_form.html.twig
Labels: bug, confirmed, finished

#2052 add missing IMG asset (adminlte)
  src/Resources/public/img/boxed-bg.jpg
Labels: bug, confirmed, finished

#2063 Allow to define the max_results option per entity
  doc/book/edit-new-configuration.rst
  doc/book/list-search-show-configuration.rst
  src/Configuration/ViewConfigPass.php
  src/Controller/AdminController.php
  src/Resources/views/default/field_association.html.twig
  tests/Configuration/fixtures/configurations/input/admin_150.yml
  tests/Configuration/fixtures/configurations/output/config_150.yml
Labels: feature, finished

#2069 fix a little typo in documentation
  doc/book/complex-dynamic-backends.rst
Labels: bug, doc

#2070 Tweaked the new form tabs feature
  doc/book/edit-new-configuration.rst
  src/Configuration/NormalizerConfigPass.php
  src/Form/EventListener/EasyAdminTabSubscriber.php
  src/Form/Type/EasyAdminFormType.php
  tests/Controller/AdvancedFormLayoutTest.php
  tests/Fixtures/App/config/config_advanced_form_layout.yml
Labels: finished

#2071 Updated the vendor name in the docs and README
  README.md
  doc/book/installation.rst
  doc/index.rst
Labels: finished

#2073 Removed AppVeyor service config
  appveyor.yml
Labels: finished

#2074 Removed the config of the Coveralls service
  .coveralls.yml
Labels: finished

#2090 Update the file paths shown in error messages to Symfony 4 dir struct…
  src/Exception/NoEntitiesConfiguredException.php
  src/Exception/UndefinedEntityException.php
Labels: bug, finished

#2086 Remove legacy BC
  src/DependencyInjection/Compiler/EasyAdminConfigPass.php
  src/DependencyInjection/EasyAdminExtension.php
  src/EventListener/ExceptionListener.php
  src/EventListener/RequestPostInitializeListener.php
  src/Form/EventListener/EasyAdminAutocompleteSubscriber.php
  src/Form/Extension/EasyAdminExtension.php
  src/Form/Type/Configurator/EntityTypeConfigurator.php
  src/Form/Type/EasyAdminAutocompleteType.php
  src/Form/Type/EasyAdminFormType.php
  src/Router/EasyAdminRouter.php
Labels: feature, finished

#2093 Remove some legacy code related to PropertyAccessor
  src/Twig/EasyAdminTwigExtension.php
Labels: finished

#2088 Remove tests for Symfony versions previous to Symfony 4
  tests/Configuration/ConfigManagerTest.php
  tests/Configuration/fixtures/configurations/input/admin_007.yml
  tests/Configuration/fixtures/configurations/input/admin_008.yml
  tests/Configuration/fixtures/configurations/input/admin_013.yml
  tests/Configuration/fixtures/configurations/input/admin_014.yml
  tests/Configuration/fixtures/configurations/input/admin_020.yml
  tests/Configuration/fixtures/configurations/input/admin_021.yml
  tests/Configuration/fixtures/configurations/input/admin_026.yml
  tests/Configuration/fixtures/configurations/output/config_007.yml
  tests/Configuration/fixtures/configurations/output/config_008.yml
  tests/Configuration/fixtures/configurations/output/config_013.yml
  tests/Configuration/fixtures/configurations/output/config_014.yml
  tests/Configuration/fixtures/configurations/output/config_020.yml
  tests/Configuration/fixtures/configurations/output/config_021.yml
  tests/Configuration/fixtures/configurations/output/config_026.yml
  tests/Controller/DisabledActionsTest.php
Labels: finished
