Repository EasyCorp/EasyAdminBundle, pull requests merged in 2018-11, with the labels that each got.

#2392 Allow pagerfanta 2
  composer.json
Labels: feature, finished

#2414 Delete old issue template
  .github/ISSUE_TEMPLATE.md
Labels: finished

#2427 Bug fix, add |raw filter for help message
  src/Resources/views/form/bootstrap_3_layout.html.twig
Labels: bug, finished

#2424 Add support for searching by multiple nested associations
  src/Search/QueryBuilder.php
Labels: feature, finished

#2429 select2 css fix
  src/Resources/public/stylesheet/select2-bootstrap.min.css
Labels: bug

#2434 Deprecated some options related to forms
  doc/book/edit-new-configuration.rst
  src/Configuration/NormalizerConfigPass.php
  tests/Configuration/ConfigManagerTest.php
  tests/Controller/AdvancedFormLayoutTest.php
  tests/Controller/FormViewTest.php
Labels: finished

#2405 Fix context menu selection loss
  src/Resources/views/default/show.html.twig
Labels: bug, finished

#2448 Fixed the handling of referer URLs in show view
  src/Resources/views/default/show.html.twig
Labels: bug, finished

#2444 Maintain the selected menu when making an empty search
  src/Controller/AdminController.php
Labels: bug, finished

#2452 Strip HTML tags from flash messages
  src/Resources/views/default/flash_messages.html.twig
Labels: finished
