Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-10, with the labels that each got.

#2952 Updated Danish translations
  src/Resources/translations/EasyAdminBundle.da.xlf
Labels: feature, finished

#2943 Added modal confirmation box for batch actions #2913
  src/Configuration/ActionConfigPass.php
  src/Resources/translations/EasyAdminBundle.en.xlf
  src/Resources/translations/EasyAdminBundle.fr.xlf
  src/Resources/views/default/includes/_batch_action_modal.html.twig
  src/Resources/views/default/list.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
  tests/Configuration/fixtures/exceptions/batch_action_ask_confirm_invalid_type.yml
Labels: feature, finished

#2959 Tweaked the "confirm action" feature of batch actions
  src/Configuration/ActionConfigPass.php
  src/Resources/translations/EasyAdminBundle.en.xlf
  src/Resources/translations/EasyAdminBundle.es.xlf
  src/Resources/translations/EasyAdminBundle.fr.xlf
  src/Resources/translations/messages.en.xlf
  src/Resources/translations/messages.es.xlf
  src/Resources/translations/messages.fr.xlf
  src/Resources/views/default/includes/_batch_action_modal.html.twig
  src/Resources/views/default/list.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
  tests/Configuration/fixtures/exceptions/batch_action_ask_confirm_invalid_type.yml
  tests/Controller/CustomizedBackendTest.php
  tests/Fixtures/App/config/config_customized_backend.yml
Labels: finished

#2960 add missing translation for continue
  src/Resources/translations/EasyAdminBundle.nl.xlf
  src/Resources/translations/messages.nl.xlf
Labels: finished

#2965 Update EasyAdminBundle.cs.xlf
  src/Resources/translations/EasyAdminBundle.cs.xlf
Labels: finished

#2962 form theme
  doc/integration/ivoryckeditorbundle.rst
Labels: doc, finished

#2966 Tweaked an exception message
  src/Configuration/ActionConfigPass.php
  tests/Configuration/fixtures/exceptions/batch_action_ask_confirm_invalid_type.yml
Labels: finished
