Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-01, with the labels that each got.

#2569 Update year in license file
  LICENSE.md
Labels: finished

#2564 2563 Add missing pl translation for paginator.results
  src/Resources/translations/EasyAdminBundle.pl.xlf
Labels: finished

#2567 Route to the new controller
  doc/book/installation.rst
Labels: doc, finished

#2576 added missing translation pt paginator.results
  src/Resources/translations/EasyAdminBundle.pt.xlf
Labels: finished

#2574 Add pl translation user.exit_impersonation
  src/Resources/translations/EasyAdminBundle.pl.xlf
Labels: finished

#2571 Fix polish translation for search.page_title and paginator.results
  src/Resources/translations/EasyAdminBundle.pl.xlf
Labels: finished

#2582 Update complex-dynamic-backends.rst
  doc/book/complex-dynamic-backends.rst
Labels: doc, finished

#2585 Add wrapper blocks and avoiding process blocks twice
  src/Resources/views/default/layout.html.twig
Labels: bug, finished

#2591 Hide the content footer in edit/new pages
  src/Resources/views/default/edit.html.twig
  src/Resources/views/default/new.html.twig
Labels: bug, finished

#2602 Added support for case insensitive text search in PostgreSQL
  src/Search/QueryBuilder.php
Labels: feature, finished

#2606 Fixed the way menu headers are displayed
  assets/css/easyadmin-theme/menu.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: finished

#2605 Disable distinct element count in paginator
  src/Search/Paginator.php
Labels: bug, finished

#2604 Pass the full item/entity to the actions template
  src/Resources/views/default/list.html.twig
  src/Resources/views/default/show.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
Labels: feature, finished
