Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-09, with the labels that each got.

#2897 Fix: typo
  assets/css/easyadmin-theme/variables.css
  doc/tutorials/tips-and-tricks.rst
  tests/Configuration/fixtures/configurations/input/admin_042.yml
  tests/Configuration/fixtures/configurations/input/admin_148.yml
  tests/Fixtures/App/config/config_empty_action_labels.yml
Labels: finished

#2919 Update EasyAdminBundle.gl.xlf
  src/Resources/translations/EasyAdminBundle.gl.xlf
Labels: finished

#2893 Make DateTimeFilterType compat with \DateTimeImmutable instances
  src/Form/Filter/Type/DateTimeFilterType.php
Labels: bug, finished

#2915 Update ViewConfigPass.php
  src/Configuration/ViewConfigPass.php
Labels: bug, finished

#2908 enhancement getSubscribedServices()
  src/Controller/EasyAdminController.php
Labels: finished

#2909 Brought back bootstrap breakpoints to the theme
  assets/css/easyadmin-theme/variables.scss
  src/Resources/public/app.css
Labels: design, finished

#2887 add block for design js assets
  src/Resources/views/default/layout.html.twig
Labels: design, feature, finished

#2924 Fixed a regression in the createOrmPaginator method
  src/Search/Paginator.php
Labels: bug, finished

#2930 Updated the Twig dependency
  composer.json
  src/Controller/AdminControllerTrait.php
Labels: finished

#2923 Allow to use other kinds of FontAwesome icons
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
Labels: bug, design, finished

#2936 Fixed the Treebuilder deprecation in 1.x branch
  src/DependencyInjection/Configuration.php
Labels: bug, finished

#2939 json pretty print
  src/Resources/views/default/field_json.html.twig
  src/Resources/views/default/field_json_array.html.twig
Labels: bug, confirmed, finished

#2937 Make EasyAdmin 1.x incompatible with Symfony 5.x
  composer.json
Labels: finished

#2926 Add form_theme_only config option
  doc/book/configuration-reference.rst
  src/DependencyInjection/Configuration.php
  src/Resources/views/default/edit.html.twig
  src/Resources/views/default/filters.html.twig
  src/Resources/views/default/list.html.twig
  src/Resources/views/default/new.html.twig
Labels: bug

#2944 Fixed an undefined property in some edge cases
  src/Configuration/ViewConfigPass.php
Labels: bug, finished

#2946 Fixed some failing tests because of recent Doctrine changes
  tests/Form/Filter/Type/ArrayFilterTypeTest.php
  tests/Form/Filter/Type/BooleanFilterTypeTest.php
  tests/Form/Filter/Type/ChoiceFilterTypeTest.php
  tests/Form/Filter/Type/ComparisonFilterTypeTest.php
  tests/Form/Filter/Type/DateTimeFilterTypeTest.php
  tests/Form/Filter/Type/EntityFilterTypeTest.php
  tests/Form/Filter/Type/FilterTypeTest.php
  tests/Form/Filter/Type/NumericFilterTypeTest.php
  tests/Form/Filter/Type/TextFilterTypeTest.php
Labels: bug, finished

#2948 Update EasyAdminBundle.cs.xlf
  src/Resources/translations/EasyAdminBundle.cs.xlf
Labels: finished

#2947 Update translations for security
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: finished
