Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-07, with the labels that each got.

#2808 Updated RU & UK translations
  src/Resources/translations/EasyAdminBundle.ru.xlf
  src/Resources/translations/EasyAdminBundle.uk.xlf
Labels: feature

#2806 Allow to define security permissions for menu items
  doc/book/menu-configuration.rst
  src/Configuration/MenuConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Resources/config/services.xml
  src/Resources/views/default/menu.html.twig
  src/Twig/EasyAdminTwigExtension.php
  tests/Configuration/fixtures/configurations/input/admin_180.yml
  tests/Configuration/fixtures/configurations/output/config_180.yml
  tests/Controller/CustomMenuSecurityTest.php
  tests/Fixtures/App/config/config_custom_menu_security.yml
Labels: feature

#2813 Fix text_editor and code_editor HTML input name
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#2814 fix(translations): fix French filters translations
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: bug, finished

#2816 feat(filters): only add placeholder for entity type if at least one join column is nullable
  src/Form/Filter/Guesser/DoctrineOrmFilterTypeGuesser.php
Labels: feature

#2824 fix(filters): test join columns only for single valued associations
  src/Form/Filter/Guesser/DoctrineOrmFilterTypeGuesser.php
Labels: bug, finished

#2823 feat(theme): add id to collections buttons add and remove
  src/Resources/views/form/bootstrap_4.html.twig
Labels: feature, finished

#2821 fix(composer): remove symfony/cache-contracts dependency
  composer.json
Labels: finished

#2820 [Doc] Fix override template property type
  doc/tutorials/custom-property-options.rst
Labels: bug, doc, finished

#2825 [Doc] simplify some docs thanks to the new options
  doc/tutorials/tips-and-tricks.rst
Labels: doc

#2817 Added some docs about the translation_domain option
  doc/book/configuration-reference.rst
  src/DependencyInjection/Configuration.php
Labels: doc, finished

#2827 Made the paginator element compatible with Bootstrap component
  UPGRADE.md
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/variables.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/paginator.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Controller/DefaultBackendTest.php
Labels: finished

#2826 update deprecated AdminController reference in docs
  doc/tutorials/custom-actions.rst
Labels: doc

#2810 Add security permissions to the "list" view
  assets/css/easyadmin-theme/datagrids.scss
  doc/book/list-search-show-configuration.rst
  doc/images/easyadmin-list-hidden-results.png
  src/Configuration/PropertyConfigPass.php
  src/Configuration/ViewConfigPass.php
  src/DependencyInjection/Configuration.php
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/translations/EasyAdminBundle.en.xlf
  src/Resources/translations/EasyAdminBundle.es.xlf
  src/Resources/views/default/list.html.twig
  tests/Configuration/fixtures/configurations/input/admin_181.yml
  tests/Configuration/fixtures/configurations/output/config_181.yml
  tests/Controller/SecurityPermissionsTest.php
  tests/Fixtures/App/config/config_security_permissions.yml
Labels: feature, finished

#2830 Minor fix in the design of exception pages
  src/Resources/views/default/exception.html.twig
Labels: design, finished

#2829 Allow to configure permissions for show/edit/new
  doc/book/edit-new-configuration.rst
  doc/book/list-search-show-configuration.rst
  src/Configuration/ViewConfigPass.php
  src/Controller/AdminControllerTrait.php
  src/Controller/EasyAdminController.php
  src/DependencyInjection/Configuration.php
  src/Exception/NoPermissionException.php
  src/Form/Type/EasyAdminFormType.php
  src/Resources/config/form.xml
  src/Resources/config/services.xml
  src/Resources/translations/EasyAdminBundle.en.xlf
  src/Resources/translations/EasyAdminBundle.es.xlf
  src/Resources/views/default/show.html.twig
  src/Security/AuthorizationChecker.php
  src/Twig/EasyAdminTwigExtension.php
  tests/Configuration/fixtures/configurations/input/admin_182.yml
  tests/Configuration/fixtures/configurations/input/admin_183.yml
  tests/Configuration/fixtures/configurations/input/admin_184.yml
  tests/Configuration/fixtures/configurations/output/config_182.yml
  tests/Configuration/fixtures/configurations/output/config_183.yml
  tests/Configuration/fixtures/configurations/output/config_184.yml
  tests/Controller/SecurityPermissionsTest.php
  tests/Fixtures/AbstractTestCase.php
  tests/Fixtures/App/config/config_security_permissions.yml
Labels: feature

#2835 Add translation fr for 'is between'
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: feature, finished

#2834 Don't hardcode the --color-primary CSS variable when unneeded
  doc/book/configuration-reference.rst
  doc/book/design-configuration.rst
  src/Resources/views/default/layout.html.twig
  tests/Controller/DefaultBackendTest.php
Labels: design, finished

#2837 Don't display "required" markers in filter labels
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: design

#2839 [Doc] Fixed the table of contents of a chapter
  doc/book/edit-new-configuration.rst
Labels: doc, finished

#2840 Fixed the default styling of the country flags in the show view
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: design, finished

#2841 Fixed the aligning of expanded choice filters
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: bug, design, finished

#2844 Allow to close flash messages
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/flash_messages.html.twig
Labels: feature, finished

#2845 Remove manual initialization for collapse and dropdown
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug, finished

#2843 Added support for append/prepend input groups
  src/Configuration/PropertyConfigPass.php
  src/Resources/views/form/bootstrap_4.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Fixtures/App/config/config_customized_backend.yml
Labels: feature, finished

#2850 Handle embedded doctrine entities
  src/Form/Type/EasyAdminFormType.php
Labels: bug

#2854 Fixed a bug related to entities with id = 0
  src/EventListener/RequestPostInitializeListener.php
Labels: bug

#2833 Add FileUploadType form type for easy file uploading
  assets/css/easyadmin-theme/forms.scss
  assets/js/app.js
  src/Controller/AdminControllerTrait.php
  src/Form/DataTransformer/StringToFileTransformer.php
  src/Form/Type/FileUploadType.php
  src/Form/Type/Model/FileUploadState.php
  src/Form/Util/FormTypeHelper.php
  src/Resources/config/form.xml
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/views/form/bootstrap_4.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: feature, finished

#2857 Show the file name in the Bootstrap custom file input
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#2865 [UX] Show the first nav tab item with errors
  src/Resources/views/default/edit.html.twig
  src/Resources/views/default/new.html.twig
Labels: feature, finished

#2861 portuguese translations for the filter component
  src/Resources/translations/EasyAdminBundle.pt.xlf
Labels: feature, finished

#2860 Added docs for the new file upload type
  doc/book/edit-new-configuration.rst
  src/Form/Util/FormTypeHelper.php
Labels: doc, finished

#2863 Fix CSS of the fileupload widget
  assets/css/easyadmin-theme/forms.scss
  src/Form/Type/FileUploadType.php
  src/Resources/public/app.css
  src/Resources/public/app.css.map
Labels: bug, finished

#2864 Verify validity for select and textarea inputs
  assets/js/form-type-code-editor.js
  src/Resources/public/form-type-code-editor.js
  src/Resources/views/default/edit.html.twig
  src/Resources/views/default/new.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#2870 [UX] Implementing visual feedback for invalid form fields (fixes #2867)
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/views/default/edit.html.twig
  src/Resources/views/default/new.html.twig
Labels: feature, finished

#2869 Support for "required" tag attribute in EasyAdminAutocompleteType
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, confirmed, finished

#2868 Minor redesign for the form collections
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/views/form/bootstrap_4.html.twig
Labels: design, finished

#2874 Including TrixEditor styles into the editor preview
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, confirmed, finished
