Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-06, with the labels that each got.

#2741 Fixed the handling of the default search sorting
  src/Controller/AdminControllerTrait.php
  src/Resources/views/default/list.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Controller/DefaultBackendTest.php
Labels: bug, finished

#2743 Fixed some minor issues in translation files
  src/Resources/translations/EasyAdminBundle.gl.xlf
  src/Resources/translations/EasyAdminBundle.lt.xlf
  src/Resources/translations/messages.gl.xlf
Labels: bug, finished

#2745 Updated the form help messages for Bootstrap 4
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/show.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Controller/FormViewTest.php
Labels: feature, finished

#2740 Add support for list filters
  assets/css/app.scss
  assets/js/app.js
  src/Configuration/NormalizerConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Configuration/TemplateConfigPass.php
  src/Controller/AdminControllerTrait.php
  src/DependencyInjection/Compiler/EasyAdminFormTypePass.php
  src/Form/Extension/EasyAdminExtension.php
  src/Form/Filter/BooleanFilter.php
  src/Form/Filter/ComparisonFilter.php
  src/Form/Filter/DateFilter.php
  src/Form/Filter/EntityFilter.php
  src/Form/Filter/Filter.php
  src/Form/Filter/FilterInterface.php
  src/Form/Filter/FilterTrait.php
  src/Form/Filter/TextFilter.php
  src/Form/Type/ComparisonEqualType.php
  src/Form/Type/ComparisonLikeType.php
  src/Form/Type/Configurator/EntityFilterConfigurator.php
  src/Form/Type/EasyAdminFiltersFormType.php
  src/Resources/config/form.xml
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/public/bootstrap-all.js
  src/Resources/translations/EasyAdminBundle.en.xlf
  src/Resources/views/default/filters.html.twig
  src/Resources/views/default/includes/_filters_modal.html.twig
  src/Resources/views/default/list.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: feature, finished

#2755 Improving the filters system
  doc/book/list-search-show-configuration.rst
  src/Configuration/NormalizerConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Controller/AdminControllerTrait.php
  src/Controller/EasyAdminController.php
  src/DependencyInjection/Compiler/FilterTypePass.php
  src/EasyAdminBundle.php
  src/Form/ChoiceList/Loader/DynamicChoiceLoader.php
  src/Form/Filter/FilterRegistry.php
  src/Form/Filter/Guesser/DoctrineOrmFilterTypeGuesser.php
  src/Form/Filter/Type/ArrayFilterType.php
  src/Form/Filter/Type/BooleanFilterType.php
  src/Form/Filter/Type/ComparisonFilterType.php
  src/Form/Filter/Type/DateTimeFilterType.php
  src/Form/Filter/Type/EntityFilterType.php
  src/Form/Filter/Type/FilterInterface.php
  src/Form/Filter/Type/FilterType.php
  src/Form/Filter/Type/FilterTypeTrait.php
  src/Form/Filter/Type/TextFilterType.php
  src/Form/Type/ComparisonEqualType.php
  src/Form/Type/ComparisonLikeType.php
  src/Form/Type/ComparisonType.php
  src/Form/Type/Configurator/EntityFilterTypeConfigurator.php
  src/Form/Type/Filter/ComparisonFilterType.php
  src/Resources/config/form.xml
  src/Resources/config/services.xml
  src/Resources/translations/EasyAdminBundle.en.xlf
  tests/Configuration/NormalizerConfigPassTest.php
  tests/Configuration/PropertyConfigPassTest.php
  tests/Configuration/fixtures/configurations/input/admin_179.yml
  tests/Configuration/fixtures/configurations/output/config_178.yml
  tests/Configuration/fixtures/configurations/output/config_179.yml
  tests/Controller/FiltersTest.php
Labels: feature, finished

#2765 Excluding the filter type guesser from the form type guessers group
  src/DependencyInjection/Compiler/FilterTypePass.php
  src/EasyAdminBundle.php
Labels: bug, finished

#2772 Making "easyadmin.filter.registry" service as public.
  src/Resources/config/form.xml
Labels: bug, finished

#2773 Translated the new filters feature into German
  src/Resources/translations/EasyAdminBundle.de.xlf
Labels: feature, finished

#2774 Add tests for filtering classes
  tests/Form/ChoiceList/Loader/DynamicChoiceLoaderTest.php
  tests/Form/Filter/FilterRegistryTest.php
  tests/Form/Filter/Fixtures/FooFilterType.php
  tests/Form/Filter/Fixtures/FoobarFilterType.php
  tests/Form/Filter/Fixtures/InvalidFilterType.php
  tests/Form/Filter/Type/ArrayFilterTypeTest.php
  tests/Form/Filter/Type/BooleanFilterTypeTest.php
  tests/Form/Filter/Type/ComparisonFilterTypeTest.php
  tests/Form/Filter/Type/DateTimeFilterTypeTest.php
  tests/Form/Filter/Type/EntityFilterTypeTest.php
  tests/Form/Filter/Type/FilterTypeTest.php
  tests/Form/Filter/Type/TextFilterTypeTest.php
Labels: finished

#2771 Translated the new filters feature into Polish
  src/Resources/translations/EasyAdminBundle.pl.xlf
Labels: feature, finished

#2749 fix(vich-uploader): fix widget display
  assets/css/easyadmin-theme/forms.scss
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#2778 Fixed typo in new.html.twig template
  src/Resources/views/default/new.html.twig
Labels: bug, finished

#2776 Removed dead code and simplification
  src/Configuration/DefaultConfigPass.php
  src/Configuration/NormalizerConfigPass.php
  src/Configuration/PropertyConfigPass.php
  src/Configuration/ViewConfigPass.php
  src/DependencyInjection/Compiler/EasyAdminFormTypePass.php
  src/Resources/config/form.xml
Labels: finished

#2780 feat(filters): add French translations
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: feature, finished

#2783 list-search-show-configuration: fix doc typo
  doc/book/list-search-show-configuration.rst
Labels: doc, finished

#2782 added italian translations
  src/Resources/translations/EasyAdminBundle.it.xlf
Labels: feature, finished

#2781 Fixed ArrayFilterType issue and add support for multiple => false
  src/Form/Filter/Type/ArrayFilterType.php
  tests/Form/Filter/Type/ArrayFilterTypeTest.php
Labels: bug, feature, finished

#2788 Added Turkish translations for filters
  src/Resources/translations/EasyAdminBundle.tr.xlf
Labels: feature

#2789 [Doc] Improve the docs about configuring the logged user info
  doc/book/basic-configuration.rst
Labels: doc

#2791 Add 'label.form.empty_value' in translation fr
  src/Resources/translations/EasyAdminBundle.fr.xlf
Labels: finished

#2794 Add support for unmapped filter fields
  doc/book/list-search-show-configuration.rst
  src/Configuration/PropertyConfigPass.php
  tests/Configuration/fixtures/exceptions/filters_unknown_property.yml
  tests/Configuration/fixtures/exceptions/filters_unmapped_without_type.yml
Labels: feature, finished

#2766 Added a "code" form type
  assets/css/easyadmin-theme/forms.scss
  assets/css/form-type-code-editor.css
  assets/js/app.js
  assets/js/form-type-code-editor.js
  doc/book/edit-new-configuration.rst
  package.json
  src/Form/Type/CodeEditorType.php
  src/Form/Type/Configurator/CodeEditorTypeConfigurator.php
  src/Form/Util/FormTypeHelper.php
  src/Resources/config/form.xml
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-code-editor.css
  src/Resources/public/form-type-code-editor.css.map
  src/Resources/public/form-type-code-editor.js
  src/Resources/public/manifest.json
  src/Resources/views/form/bootstrap_4.html.twig
  webpack.config.js
  yarn.lock
Labels: feature

#2804 Add missing translations for nl
  src/Resources/translations/EasyAdminBundle.nl.xlf
Labels: feature

#2756 Form tabs - handling css_class parameter for form tabs
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished
