Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-02, with the labels that each got.

#2578 Introduce batch action feature
  assets/css/easyadmin-theme/base.scss
  src/Configuration/ActionConfigPass.php
  src/Configuration/NormalizerConfigPass.php
  src/Controller/AdminControllerTrait.php
  src/DependencyInjection/Configuration.php
  src/Form/Type/EasyAdminBatchFormType.php
  src/Resources/config/form.xml
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/list.html.twig
  src/Resources/views/form/bootstrap_4.html.twig
Labels: feature, finished

#2611 Deal with "uuid" postgres data type
  src/Search/QueryBuilder.php
Labels: feature, finished

#2609 Remove the menu backdrop element on click/toggle
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug, finished

#2514 Added some tests about custom templates and form views
  tests/Configuration/fixtures/configurations/input/admin_151.yml
  tests/Configuration/fixtures/configurations/output/config_151.yml
Labels: finished

#2617 Restrict css selector for form-tabs to avoid overloading too much style
  assets/css/easyadmin-theme/forms.scss
Labels: bug

#2618 Enable distinct element count in paginator for some cases
  src/Search/Paginator.php
Labels: bug

#2615 Allow to configure the information displayed for logged in users
  assets/css/easyadmin-theme/base.scss
  doc/book/basic-configuration.rst
  doc/book/configuration-reference.rst
  src/DependencyInjection/Configuration.php
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/layout.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: feature

#2620 Collapsible actions for rows in list/search
  assets/css/easyadmin-theme/datagrids.scss
  assets/js/app.js
  src/Configuration/ActionConfigPass.php
  src/DependencyInjection/Configuration.php
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/public/bootstrap-all.js
  src/Resources/views/default/includes/_actions.html.twig
  src/Resources/views/default/includes/_actions_dropdown.html.twig
  src/Resources/views/default/list.html.twig
  tests/Controller/CustomizedBackendTest.php
  tests/Fixtures/App/config/config_customized_backend.yml
Labels: feature, finished

#2623 Fix namespace in "New Base Controller" section
  UPGRADE-2.0.md
Labels: doc

#2607 Improving the use of Data-Transfer-Object on new/edit actions
  src/Form/Type/EasyAdminFormType.php
  src/Resources/views/form/bootstrap_4.html.twig
  tests/Controller/DataTransferObjectTest.php
  tests/Fixtures/App/config/config_data_transfer_object.yml
  tests/Fixtures/AppTestBundle/Admin/ProductController.php
  tests/Fixtures/AppTestBundle/Form/Data/AddProductData.php
  tests/Fixtures/AppTestBundle/Form/Data/UpdateProductNameData.php
Labels: feature, finished

#2629 Add box shadow and fixed column width for actions dropdown
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/views/default/list.html.twig
Labels: finished

#2603 Don't use "absolute path" for assets
  src/Resources/public/app-rtl.js
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/app.js
  src/Resources/public/bootstrap-all.js
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  webpack.config.js
Labels: bug, finished

#2644 Fix some JavaScript issues for some special pages
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug
