Repository EasyCorp/EasyAdminBundle, pull requests merged in 2019-04, with the labels that each got.

#2693 fix(help-text): use form translation domain
  src/Resources/views/form/bootstrap_3_horizontal_layout.html.twig
  src/Resources/views/form/bootstrap_3_layout.html.twig
Labels: bug, confirmed, finished

#2699 Upgrade of Font Awesome to v5.8
  assets/css/app.scss
  package.json
  src/Resources/public/app.css
  src/Resources/public/app.css.map
  src/Resources/public/fonts/fa-brands-400.2ef8ba34.woff
  src/Resources/public/fonts/fa-brands-400.5e2f9212.woff2
  src/Resources/public/fonts/fa-brands-400.98b6db59.ttf
  src/Resources/public/fonts/fa-brands-400.a7b95dbd.eot
  src/Resources/public/fonts/fa-regular-400.427d721b.woff
  src/Resources/public/fonts/fa-regular-400.65b9977a.ttf
  src/Resources/public/fonts/fa-regular-400.dcce4b7f.eot
  src/Resources/public/fonts/fa-regular-400.e6257a72.woff2
  src/Resources/public/fonts/fa-solid-900.418dad87.woff2
  src/Resources/public/fonts/fa-solid-900.46e7cec6.eot
  src/Resources/public/fonts/fa-solid-900.a7140145.woff
  src/Resources/public/fonts/fa-solid-900.ff8d9f8a.ttf
  src/Resources/public/fonts/fontawesome-webfont.674f50d2.eot
  src/Resources/public/fonts/fontawesome-webfont.af7ae505.woff2
  src/Resources/public/fonts/fontawesome-webfont.b06871f2.ttf
  src/Resources/public/fonts/fontawesome-webfont.fee66e71.woff
  src/Resources/public/images/fa-brands-400.5bf14553.svg
  src/Resources/public/images/fa-regular-400.5eb754ab.svg
  src/Resources/public/images/fa-solid-900.49279363.svg
  src/Resources/public/images/fontawesome-webfont.912ec66d.svg
  src/Resources/public/manifest.json
  yarn.lock
Labels: feature

#2705 Filled missing Lithuanian translations.
  src/Resources/translations/EasyAdminBundle.lt.xlf
Labels: finished

#2700 Fixed width for action icons in list view
  src/Resources/views/default/includes/_actions.html.twig
  tests/Controller/EmptyActionLabelsTest.php
Labels: bug, finished

#2697 fix(image-preview): support svg
  src/Resources/views/css/easyadmin.css.twig
Labels: bug, finished
