Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-12, with the labels that each got.

#4001 Do not drop specific css class on transform field
  src/Factory/FieldFactory.php
Labels: bug, confirmed

#4005 fix #4003 : Add trim on search queries
  src/Dto/SearchDto.php
Labels: bug, confirmed

#4023 Fixed variable typo in doc
  doc/actions.rst
Labels: doc

#4015 [Doc] clarify the purpose of the menu item permission
  doc/security.rst
Labels: doc

#4025 Don't display form errors twice
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4031 layout.html.twig: add a Twig block encapsulating the <meta> tags
  src/Resources/views/layout.html.twig
Labels: design, feature

#4030 CommonPostConfigurator: fix some issues (particularly bring by #3982)
  src/Dto/FieldDto.php
  src/Field/Configurator/CommonPostConfigurator.php
Labels: bug

#4057 fixes #4040
  src/Command/MakeAdminDashboardCommand.php
Labels: bug

#4054 Deprecate CRUD ID in admin URLs
  UPGRADE.md
  src/Config/Menu/CrudMenuItem.php
  src/Controller/AbstractCrudController.php
  src/EventListener/AdminRouterSubscriber.php
  src/Factory/ActionFactory.php
  src/Factory/ControllerFactory.php
  src/Field/Configurator/AssociationConfigurator.php
  src/Inspector/DataCollector.php
  src/Resources/views/crud/includes/_delete_form.html.twig
  src/Router/AdminUrlGenerator.php
Labels: feature

#4062 Add a signature to all backend URLs
  doc/dashboards.rst
  src/Config/Dashboard.php
  src/Config/Option/EA.php
  src/Context/AdminContext.php
  src/Dto/DashboardDto.php
  src/EventListener/AdminRouterSubscriber.php
  src/Factory/ActionFactory.php
  src/Factory/MenuFactory.php
  src/Orm/EntityPaginator.php
  src/Resources/config/services.php
  src/Resources/views/crud/includes/_delete_form.html.twig
  src/Resources/views/crud/index.html.twig
  src/Router/AdminUrlGenerator.php
  src/Router/CrudUrlBuilder.php
  src/Router/CrudUrlGenerator.php
  src/Router/UrlSigner.php
  src/Twig/EasyAdminTwigExtension.php
  tests/Router/AdminUrlGeneratorTest.php
  tests/Router/UrlSignerTest.php
  tests/TestApplication/src/Controller/AnotherDashboardController.php
Labels: feature

#4067 Fixed some misc routing issues
  UPGRADE.md
  src/EventListener/AdminRouterSubscriber.php
  src/Field/BooleanField.php
  src/Field/Configurator/BooleanConfigurator.php
  src/Resources/config/services.php
  src/Resources/views/crud/field/boolean.html.twig
  src/Resources/views/crud/index.html.twig
  src/Router/CrudUrlBuilder.php
Labels: bug

#4068 render form errors for CRUD form types again
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4059 Fix issue in CommonPostConfigurator
  src/Field/Configurator/CommonPostConfigurator.php
Labels: bug

#4080 Fixed typos on adminUrlGenerator in UPGRADE.md
  UPGRADE.md
Labels: doc

#4082 fix deprecating the CRUD URL generator service
  src/Resources/config/services.php
Labels: bug

#4083 Fixed admin URL generation in tests
  src/Router/AdminUrlGenerator.php
  src/Router/CrudUrlBuilder.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: bug

#4071 renderFilters form action query fix
  src/Controller/AbstractCrudController.php
Labels: bug

#4058 Check if join has been added earlier in the building of the query
  src/Orm/EntityRepository.php
Labels: bug

#4061 ImageField Multiple - Fix GetImagePath
  src/Field/Configurator/ImageConfigurator.php
Labels: bug

#4087 fix undefined variable $aliases
  src/Orm/EntityRepository.php
Labels: bug
