Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-05, with the labels that each got.

#3164 [3.0] Add SlugField
  assets/css/easyadmin-theme/forms.scss
  assets/js/form-type-slug.js
  doc/fields.rst
  package.json
  src/Field/SlugField.php
  src/Form/Type/SlugType.php
  src/Resources/public/app.css
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-slug.js
  src/Resources/public/manifest.json
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.bg.php
  src/Resources/translations/EasyAdminBundle.ca.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.eu.php
  src/Resources/translations/EasyAdminBundle.fa.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.gl.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.it.php
  src/Resources/translations/EasyAdminBundle.lt.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.sl.php
  src/Resources/translations/EasyAdminBundle.sr_RS.php
  src/Resources/translations/EasyAdminBundle.sv.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.uk.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
  src/Resources/views/crud/form_theme.html.twig
  webpack.config.js
  yarn.lock
Labels: feature

#3168 Fix a display glitch when using a textarea in the default show fields
  src/Resources/views/default/field_json.html.twig
  src/Resources/views/default/field_json_array.html.twig
Labels: bug, finished

#3173 Migrate array to ArrayField
  src/Field/ArrayField.php
  src/Maker/Migrator.php
  tests/Maker/fixtures/output/ProductCrudController.php
Labels: bug

#3175 Fix doc example
  doc/dashboards.rst
Labels: doc

#3183 [Doc] Fix example to update an action
  doc/actions.rst
Labels: doc

#3182 Fixed front-end dependencies issues
  package.json
  src/Resources/public/app.js
  yarn.lock
Labels: bug

#3190 Add support for links to a URL
  doc/actions.rst
  src/Config/Action.php
  src/Dto/ActionDto.php
  src/Factory/ActionFactory.php
Labels: feature

#3193 Allow to configure the whole form options (e.g. validation_groups)
  doc/crud.rst
  src/Config/Crud.php
  src/Contracts/Controller/CrudControllerInterface.php
  src/Controller/AbstractCrudController.php
  src/Dto/CrudDto.php
  src/Factory/FormFactory.php
Labels: bug

#3195 Don't translate labels in form pages because Symfony Form does that
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#3202 Re-enable persist in updateEntity()
  src/Controller/AbstractCrudController.php
Labels: bug

#3205 Fix form type options when using DateTimeImmutable
  src/Form/Type/CrudFormType.php
Labels: bug

#3194 Fixed some issues in SelectField
  src/Field/Configurator/SelectConfigurator.php
  src/Field/SelectField.php
Labels: bug

#3209 Fixed a bug related to fields without permission
  src/Collection/EntityCollection.php
  src/Collection/FieldCollection.php
  src/Controller/AbstractCrudController.php
  src/Dto/EntityDto.php
  src/Exception/InsufficientEntityPermissionException.php
  src/Factory/EntityFactory.php
  src/Factory/FieldFactory.php
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.bg.php
  src/Resources/translations/EasyAdminBundle.ca.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.eu.php
  src/Resources/translations/EasyAdminBundle.fa.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.gl.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.it.php
  src/Resources/translations/EasyAdminBundle.lt.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.sl.php
  src/Resources/translations/EasyAdminBundle.sr_RS.php
  src/Resources/translations/EasyAdminBundle.sv.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.uk.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
Labels: bug

#2969 Tips and tricks: Factorize configuration instead of repeating it
  doc/tutorials/tips-and-tricks.rst
Labels: doc

#2990 Add parameter support for routes
  .gitignore
  src/Resources/views/default/includes/_actions.html.twig
Labels: feature

#3213 [3.0] Preventing non-string type from being used as array key
  src/Collection/EntityCollection.php
  src/Factory/EntityFactory.php
Labels: bug

#3219 Fixed a bug related to actions of entities without permission
  src/Factory/ActionFactory.php
Labels: bug

#3221 Fixed minor typo in docs
  doc/book/edit-new-configuration.rst
Labels: doc

#3220 Allow to render ChoiceField values as badges
  assets/css/easyadmin-theme/badges.scss
  assets/css/easyadmin-theme/theme.scss
  assets/css/easyadmin-theme/variables.css
  assets/css/easyadmin-theme/variables.scss
  src/Field/ChoiceField.php
  src/Field/Configurator/ChoiceConfigurator.php
  src/Registry/TemplateRegistry.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/crud/field/choice.html.twig
  src/Resources/views/crud/index.html.twig
  yarn.lock
Labels: design, feature, finished

#3222 [3.0] Choices should be translated using the correct translation domain
  src/Field/Configurator/ChoiceConfigurator.php
Labels: bug

#3226 Use the configured translation domain to translate some labels
  src/Factory/AdminContextFactory.php
Labels: bug

#3229 Fixed an edge-case related to fields and form panels
  src/Collection/FieldCollection.php
  src/Dto/FieldDto.php
  src/Factory/FieldFactory.php
  src/Field/FormField.php
Labels: bug

#3230 Fixed a Doctrine data type check in DateTime field configurator
  src/Field/Configurator/DateTimeConfigurator.php
Labels: bug

#3231 Improved the docs about security and custom voters
  doc/security.rst
Labels: doc

#3233 Fixed error when there is no crud controller yet
  src/Registry/CrudControllerRegistry.php
Labels: bug

#3234 Fixed crud controller template
  src/Resources/skeleton/crud_controller.tpl
Labels: bug

#3238 fix syntax errors
  src/Resources/translations/EasyAdminBundle.ar.xlf
Labels: bug

#3240 Add empty collection label/attr in collection fields only
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#3241 Fixed select2 dropdown zindex
  assets/css/easyadmin-theme/select2.scss
  assets/css/easyadmin-theme/variables.css
  src/Resources/public/app.css
Labels: bug

#3247 fix class name error
  doc/dashboards.rst
Labels: doc

#3249 [3.0] Fixed translation domain for Slug confirm text
  src/Field/Configurator/SlugConfigurator.php
Labels: bug

#3244 Fix issue with CollectionField
  assets/js/form-type-collection.js
Labels: bug

#3251 Added some methods to display fields conditionally
  src/Dto/FieldDto.php
  src/Factory/FieldFactory.php
  src/Field/FieldTrait.php
Labels: feature

#3252 Fixed a bug of primary keys with typed properties
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug

#3253 Fixed some issues related to the menu
  src/Factory/MenuFactory.php
  src/Router/CrudUrlBuilder.php
Labels: bug

#3258 Fix typo in doc
  doc/filters.rst
Labels: doc

#3254 [3.0] Fixed crud index toggler on refresh for Firefox
  src/Resources/views/crud/field/boolean.html.twig
Labels: bug

#3259 Don't translate choice values passed to Symfony forms
  src/Field/Configurator/ChoiceConfigurator.php
Labels: bug

#3272 Minor change - crud.rst
  doc/crud.rst
Labels: doc

#3262 Fixed the detection of the dashboard route
  src/Cache/CacheWarmer.php
  src/Factory/AdminContextFactory.php
  src/Resources/config/services.php
Labels: bug

#3271 Use the configured translation domain for forms too
  src/Contracts/Controller/CrudControllerInterface.php
  src/Controller/AbstractCrudController.php
  src/Factory/FormFactory.php
Labels: bug

#3277 Fixed the use of menu sections without labels in user menus
  src/Config/Action.php
  src/Config/Actions.php
  src/Config/Menu/SectionMenuItem.php
  src/Config/MenuItem.php
  src/Dto/ActionDto.php
Labels: bug

#3280 Aadd more tags automatically to certain services
  src/DependencyInjection/EasyAdminExtension.php
  src/Resources/config/services.php
Labels: feature

#3288 FIx Events doc
  doc/events.rst
Labels: doc

#3285 Hide form panels by default in index pages
  src/Field/FormField.php
Labels: bug, design

#3287 [3.0] Fixed Actions docs
  doc/actions.rst
Labels: doc

#3292 Improved the docs of the entity filters
  doc/book/list-search-show-configuration.rst
Labels: doc
