Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-03, with the labels that each got.

#3084 Fix missed ukrainian translation
  src/Resources/translations/EasyAdminBundle.uk.xlf
Labels: finished

#3074 Update installation.rst
  doc/book/installation.rst
Labels: doc, finished

#3085 fix uk plural
  src/Resources/translations/EasyAdminBundle.uk.xlf
Labels: bug, finished
