Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-11, with the labels that each got.

#3925 Fixed the placeholder option of choice fields
  assets/js/app.js
  src/Field/Configurator/ChoiceConfigurator.php
  src/Resources/public/app.js
  tests/Field/ChoiceFieldTest.php
Labels: bug

#3929 [ChoiceField] Allow to define choices using a callback
  src/Field/ChoiceField.php
  src/Field/Configurator/ChoiceConfigurator.php
  tests/Field/ChoiceFieldTest.php
Labels: feature

#3935 Try to run tests in all operating systems
  .github/workflows/ci.yaml
  tests/Maker/MigratorTest.php
Labels: help wanted

#3604 Allow to define dynamic labels and page titles
  doc/crud.rst
  src/Config/Action.php
  src/Config/Crud.php
  src/Dto/CrudDto.php
  src/Factory/ActionFactory.php
  src/Factory/AdminContextFactory.php
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/new.html.twig
  tests/Intl/IntlFormatterTest.php
Labels: feature

#3951 Don't override the query_builder form option in associations
  src/Field/Configurator/AssociationConfigurator.php
Labels: bug

#3833 Automatically check and create given controller directory
  src/Command/MakeAdminDashboardCommand.php
Labels: feature

#3479 CSP: wrap script tags rendered on page load in blocks to allow manual overwrite
  src/Resources/views/crud/includes/_filters_modal.html.twig
  src/Resources/views/layout.html.twig
Labels: feature

#3644 Allow to render HTML in options - ChoiceField
  assets/css/easyadmin-theme/select2.scss
  assets/js/app.js
  src/Field/ChoiceField.php
  src/Field/Configurator/ChoiceConfigurator.php
  src/Resources/public/app.css
  src/Resources/public/app.js
Labels: feature

#3955 Display flags in country dropdowns
  assets/css/easyadmin-theme/fields.scss
  assets/images/flags/GENERIC.png
  assets/images/flags/UNKNOWN.png
  src/Field/Configurator/CountryConfigurator.php
  src/Field/CountryField.php
  src/Resources/config/services.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/images/flags/GENERIC.png
  src/Resources/public/images/flags/UNKNOWN.png
  src/Resources/public/manifest.json
  tests/Field/ChoiceFieldTest.php
Labels: feature

#3960 Bugfix for default content/sidebar width
  src/Dto/CrudDto.php
Labels: bug

#3959 Prevent Panel renderCollapsed and Textarea Autogrow clash
  assets/js/form-type-textarea.js
Labels: bug, design

#3957 Fixed the autocomplete feature of association fields
  src/Controller/AbstractCrudController.php
  src/Field/Configurator/AssociationConfigurator.php
Labels: bug

#3958 #3956 Added support to use callable formats in routing configuration
  src/Cache/CacheWarmer.php
Labels: bug

#3944 Fixed "allowClear" when no "placeholder" is set (AssociationField)
  src/Form/Type/CrudAutocompleteType.php
Labels: bug

#3962 Allow to upload/remove images in Image fields
  src/Controller/AbstractCrudController.php
  src/Field/Configurator/ImageConfigurator.php
  src/Field/ImageField.php
  src/Form/DataTransformer/StringToFileTransformer.php
  src/Form/Type/FileUploadType.php
  src/Resources/config/services.php
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#3972 Improve doc - custom action
  doc/actions.rst
Labels: doc

#3971 Improved documentation for reorder
  doc/actions.rst
Labels: doc

#3980 Highlight form help when a field is focused
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
Labels: design, feature

#3977 Add section before logout and exit impersonation
  src/Controller/AbstractDashboardController.php
Labels: design, feature

#3982 Display formatted field values as "raw" values in templates
  src/Field/Configurator/CommonPostConfigurator.php
  src/Resources/config/services.php
Labels: feature

#3994 [Minor] Updated method visibility in custom crudAction doc
  doc/actions.rst
Labels: doc

#3991 Fix #3990 - ImageField Filename Erased
  src/Form/DataTransformer/StringToFileTransformer.php
Labels: bug, confirmed
