Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-06, with the labels that each got.

#3298 [3.0] Fixed deprecations for Symfony 5.1
  src/Factory/AdminContextFactory.php
Labels: bug

#3301 Fixed some issues related to filters
  doc/fields.rst
  src/Factory/FieldFactory.php
  src/Field/Configurator/CommonPostConfigurator.php
Labels: bug

#3303 Fix a few minor misprints in docs
  doc/dashboards.rst
Labels: doc

#3310 Fix broken link to the next section
  doc/design.rst
Labels: doc

#3312 Allow to search using nested associations
  src/Orm/EntityRepository.php
  src/Resources/config/services.php
Labels: bug

#3313 Fix incorrect filter class name in example in docs
  doc/filters.rst
Labels: doc

#3314 Fix missing ticks in the docs
  doc/crud.rst
Labels: doc

#3315 Fixed the way Dashboard route names are found
  src/Cache/CacheWarmer.php
  src/Factory/AdminContextFactory.php
Labels: bug

#3321 Fix doc examle
  doc/fields.rst
Labels: doc

#3335 Support DELETE with http_method_override disabled
  src/Controller/AdminControllerTrait.php
Labels: bug

#3338 Made the login page independent from Dashboards
  doc/dashboards.rst
  src/Resources/views/page/login.html.twig
  src/Resources/views/page/login_minimal.html.twig
Labels: feature

#3340 Fixed the menu items of type URL
  src/Factory/MenuFactory.php
Labels: bug

#3341 Allow using showOn and hideOn methods in generic Field objects
  src/Factory/FieldFactory.php
Labels: bug

#3342 Improving Bulgarian translation
  src/Resources/translations/EasyAdminBundle.bg.php
Labels: feature

#3346 form theme works without crud controller
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#3350 Fix doc example
  doc/design.rst
  doc/fields.rst
Labels: doc

#3351 [Doc] Fix link to Permission class
  doc/security.rst
Labels: doc

#3358 Add forgotten closing quotes
  doc/dashboards.rst
Labels: doc

#3362 Update crud.rst
  doc/crud.rst
Labels: doc

#3356 [Doc] Built-in action permission method fix + typo
  doc/security.rst
Labels: doc

#3360 Fixed block prefixes order of the CollectionType
  src/Form/Extension/CollectionTypeExtension.php
Labels: bug, finished

#3375 Fix PHP 7.2 compatibility, add test for legacy controller
  .gitignore
  .php_cs
  phpunit.xml.dist
  src/Command/MakeAdminMigrationCommand.php
  src/Controller/EasyAdminController.php
  src/DependencyInjection/EasyAdminExtension.php
  src/Dto/CrudDto.php
  src/Dto/UserMenuDto.php
  src/Field/Configurator/ArrayConfigurator.php
  src/Orm/EntityRepository.php
  tests/Controller/EasyAdminControllerTest.php
Labels: bug

#3361 Fixed Dashboard Crud links when using prefixed routes
  src/Cache/CacheWarmer.php
  src/Factory/AdminContextFactory.php
Labels: bug

#3368 HTTP Basic Auth Documentation
  .vscode/settings.json
  doc/dashboards.rst
Labels: doc

#3381 Mention setFaviconPath() method
  doc/upgrade.rst
Labels: doc

#3377 Update MenuFactory.php
  src/Factory/MenuFactory.php
Labels: bug

#3385 Configured the currency property in the MoneyField form type
  src/Field/Configurator/MoneyConfigurator.php
Labels: bug

#3387 Fix: Code
  doc/filters.rst
Labels: doc

#3398 Fix: Action
  doc/actions.rst
Labels: doc

#3396 [+] Fix Russian translation.
  src/Resources/translations/EasyAdminBundle.ru.php
Labels: feature

#3395 Fixed action template
  src/Resources/views/crud/action.html.twig
Labels: bug

#3403 Fixed the make:admin:crud command when there are no entities
  src/Command/MakeCrudControllerCommand.php
Labels: bug

#3401 Reordering Action - Issue #3369
  src/Config/Actions.php
  src/Dto/ActionConfigDto.php
Labels: bug

#3386 Fixed the NumberField when number of decimals is not specified
  src/Field/Configurator/NumberConfigurator.php
Labels: bug

#3407 Fix text documentation
  doc/upgrade.rst
Labels: doc

#3409 [Doc] Fixed referencing articles in toctree
  doc/index.rst
Labels: bug, doc

#3408 Don't use autocomplete callback in the migration command
  src/Command/MakeAdminMigrationCommand.php
Labels: bug

#3410 Fixed the dropdown menu of entity actions
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#3411 Avoid translating empty strings
  src/Factory/ActionFactory.php
  src/Factory/MenuFactory.php
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#3414 [Doc] Fix 'generate CRUD urls' 404 link
  doc/dashboards.rst
Labels: doc

#3420 [3.0] Migration: fix file name not matching class name
  src/Maker/Migrator.php
Labels: bug

#3422 Show the default sorting in the index view
  src/Dto/SearchDto.php
  src/Resources/views/crud/index.html.twig
Labels: bug

#3431 Correct block names in welcome page
  src/Resources/views/welcome.html.twig
Labels: bug
