Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-02, with the labels that each got.

#3066 Add norwegian translations
  src/Resources/translations/EasyAdminBundle.no.xlf
  src/Resources/translations/messages.no.xlf
Labels: finished

#3061 Adds missing Czech translations
  src/Resources/translations/EasyAdminBundle.cs.xlf
  src/Resources/translations/messages.cs.xlf
Labels: feature, finished

#3064 Fix correct datatype for Code Editor
  assets/js/form-type-code-editor.js
Labels: bug, finished
