Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-10, with the labels that each got.

#3850 #3513 Show generic flag when user select country which has no asset
  src/Field/Configurator/CountryConfigurator.php
  src/Resources/public/images/flags/GENERIC.png
Labels: feature

#3854 Fixed CountryConfigurator edge-case when the flag code is empty
  src/Field/Configurator/CountryConfigurator.php
Labels: bug

#3858 Use PercentType option only if it's defined by Symfony
  src/Field/Configurator/PercentConfigurator.php
Labels: bug

#3860 enable unsaved changes alert for TrixEditor fields
  assets/js/form-type-text-editor.js
  src/Resources/public/form-type-text-editor.js
Labels: bug

#3864 Allow search by nested associations of more than 2 levels
  src/Orm/EntityRepository.php
Labels: feature, finished

#3828 Fixed sorting of to-many properties
  src/Orm/EntityRepository.php
Labels: bug

#3842 #3841 fixed problem with RTL not working correctly
  src/Resources/views/layout.html.twig
Labels: bug

#3539 Add collapsible panels
  assets/css/easyadmin-theme/fields.scss
  src/Field/FormField.php
  src/Form/Type/CrudFormType.php
  src/Resources/public/app.css
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#3873 Added the generic flag to the original set of flags
  assets/images/flags/GENERIC.png
Labels: bug

#3872 Fixed compatibility with different Pagerfanta versions
  src/Search/Paginator.php
Labels: bug

#3875 Fixed some properties of the fields generated automatically
  src/Factory/FieldFactory.php
Labels: bug

#3876 Fixed deprecated non-string from InputBag::get()
  src/Resources/views/crud/index.html.twig
Labels: bug

#3885 Made Boolean fields respect the disabled form option
  src/Resources/views/crud/field/boolean.html.twig
Labels: bug

#3886 #3879 - Fix problem with ordering of associations and association properties
  src/Orm/EntityRepository.php
Labels: bug

#3890 Fixed locale consistency when generating urls
  src/Factory/AdminContextFactory.php
  src/Router/CrudUrlBuilder.php
Labels: bug

#3899 Added a sprintf, fixing the "Wrong parameters for InvalidArgumentExce…
  src/Field/Configurator/BooleanConfigurator.php
Labels: bug

#3896 Update index.rst
  doc/index.rst
Labels: doc

#3893 :bug: fix #3660, guessed namespace had an extra backslash
  src/Command/MakeAdminDashboardCommand.php
Labels: bug

#3900 Fixed an edge-case related to cache warmer
  src/Registry/DashboardControllerRegistry.php
Labels: bug

#3907 [doc] fix a small typo in CRUD
  doc/crud.rst
Labels: doc

#3904 Add twig block to customize only the header navbar
  src/Resources/views/layout.html.twig
Labels: feature

#3924 Fixed some issues in the docs
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/fields.rst
  doc/security.rst
Labels: doc

#3921 Fix controller to use DataMapper
  src/Controller/AbstractCrudController.php
Labels: bug
