Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-08, with the labels that each got.

#3639 Display the column of actions in index page unconditionally
  src/Resources/views/crud/index.html.twig
Labels: bug

#3651 Show "field required" error messages for text editors
  assets/js/form-type-text-editor.js
  src/Resources/public/form-type-text-editor.js
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/form_theme.html.twig
  src/Resources/views/crud/new.html.twig
Labels: bug

#3650 Allow clear on non required association
  assets/js/app.js
  src/Field/Configurator/AssociationConfigurator.php
Labels: feature

#3658 Fixed paginator when using HAVING conditions
  src/Orm/EntityPaginator.php
Labels: bug

#3668 Declaration of configureAssets is not compatible with DashboardController
  doc/upgrade.rst
Labels: doc

#3713 Fix incorrect interface name in docs to DashboardControllerInterface
  doc/dashboards.rst
Labels: doc

#3681 Update comment in custom action
  doc/tutorials/custom-actions.rst
Labels: doc

#3698 Allow doctrine/persistence 2.x
  composer.json
  src/Command/MakeCrudControllerCommand.php
  src/Dto/EntityDto.php
  src/Factory/EntityFactory.php
  src/Orm/EntityRepository.php
  tests/Form/Filter/Type/EntityFilterTypeTest.php
  tests/Form/Type/EasyAdminAutocompleteTypeTest.php
Labels: bug

#3712 Update turkish translation.
  src/Resources/translations/EasyAdminBundle.tr.php
Labels: bug

#3710 Update content.html.twig
  src/Resources/views/page/content.html.twig
Labels: design, feature

#3692 [Bug] Fix broken link to VichUploaderBundle docs on github
  doc/integration/vichuploaderbundle.rst
Labels: doc
