Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-04, with the labels that each got.

#3115 [3.0] Fix migrator disabled actions
  src/Maker/Migrator.php
Labels: bug

#3098 Remove FlattenExceptionTrait
  composer.json
  src/Exception/FlattenException.php
  src/Exception/FlattenExceptionTrait.php
Labels: bug

#3119 Added support for the IS_IMPERSONATOR permission
  src/Resources/views/layout.html.twig
  src/Security/SecurityVoter.php
Labels: bug, finished

#3118 Added support for the new IS_IMPERSONATOR permission
  src/Resources/views/default/layout.html.twig
Labels: bug, finished

#3113 Don't try to render rendered fields
  src/Resources/views/form/bootstrap_4.html.twig
Labels: bug, finished

#3120 Updated some error messages in tests for the latest Symfony changes
  tests/Configuration/fixtures/exceptions/action_global_format.yml
  tests/Configuration/fixtures/exceptions/batch_action_global_format.yml
  tests/Controller/SplitConfigurationTest.php
Labels: bug, finished

#2967 [3.0] Updated the docs for EasyAdmin 3
  doc/actions.rst
  doc/book/actions-configuration.rst
  doc/book/basic-configuration.rst
  doc/book/complex-dynamic-backends.rst
  doc/book/configuration-reference.rst
  doc/book/design-configuration.rst
  doc/book/edit-new-configuration.rst
  doc/book/installation.rst
  doc/book/list-search-show-configuration.rst
  doc/book/menu-configuration.rst
  doc/book/your-first-backend.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/design.rst
  doc/events.rst
  doc/fields.rst
  doc/filters.rst
  doc/images/easyadmin-boolean-field-label.png
  doc/images/easyadmin-boolean-field-toggle-error.gif
  doc/images/easyadmin-boolean-field-toggle.gif
  doc/images/easyadmin-default-backend.png
  doc/images/easyadmin-edit-view.png
  doc/images/easyadmin-form-complex-layout.png
  doc/images/easyadmin-form-group.png
  doc/images/easyadmin-form-section.png
  doc/images/easyadmin-form-tabs.png
  doc/images/easyadmin-list-hidden-results.png
  doc/images/easyadmin-list-view-actions.png
  doc/images/easyadmin-list-view.png
  doc/images/easyadmin-listing-actions-label-only.png
  doc/images/easyadmin-new-view.png
  doc/images/easyadmin-promo.png
  doc/images/easyadmin-search-view.png
  doc/images/easyadmin-show-view.png
  doc/images/wysiwyg/default-textarea.png
  doc/images/wysiwyg/default-wysiwyg.png
  doc/images/wysiwyg/simple-wysiwyg.png
  doc/index.rst
  doc/integration/fosrestbundle.rst
  doc/integration/fosuserbundle.rst
  doc/integration/ivoryckeditorbundle.rst
  doc/integration/vichuploaderbundle.rst
  doc/misc/about.rst
  doc/security.rst
  doc/tutorials/complex-backend-config.rst
  doc/tutorials/custom-actions.rst
  doc/tutorials/custom-property-options.rst
  doc/tutorials/i18n.rst
  doc/tutorials/tips-and-tricks.rst
  doc/upgrade.rst
Labels: doc, finished

#3124 Make SUCCESS and FAILURE public for Symfony 5.1
  src/Command/MakeAdminMigrationCommand.php
Labels: bug, finished

#3128 Misc. doc fixes and improvements
  doc/actions.rst
  doc/dashboards.rst
  doc/fields.rst
  doc/index.rst
Labels: doc

#3130 Fixed the cloning of FieldDto objects
  src/Dto/FieldDto.php
Labels: bug, finished

#3132 Fixed some translation keys
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
Labels: bug, finished

#3135 Misc. doc fixes
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/design.rst
  doc/fields.rst
  doc/security.rst
Labels: doc

#3136 Fixed the creation of new entities
  src/Controller/AbstractCrudController.php
Labels: bug, finished

#3138 Update easyadmin-promo.png URL (master -> 2.x)
  README.md
Labels: bug, doc, finished

#3137 [3.0] Make ea2 backup file configurable in MakeAdminMigrationCommand
  src/Command/MakeAdminMigrationCommand.php
Labels: feature

#3139 Improve migration command for multiple entities related to same class
  src/Maker/Migrator.php
Labels: bug

#3142 Fix the jQuery issue with Bootstrap 4
  package.json
  src/Resources/public/app.js
  src/Resources/public/form-type-code-editor.js
  yarn.lock
Labels: bug

#3144 Add a method to define the entity FQCN of the CRUD controller
  doc/crud.rst
  doc/fields.rst
  src/Contracts/Controller/CrudControllerInterface.php
  src/Controller/AbstractCrudController.php
  src/Maker/CodeBuilder.php
  src/Maker/Migrator.php
  src/Registry/CrudControllerRegistry.php
  tests/Maker/fixtures/output/CategoryCrudController.php
  tests/Maker/fixtures/output/ProductCrudController.php
  tests/Maker/fixtures/output/PurchaseCrudController.php
  tests/Maker/fixtures/output/PurchaseItemCrudController.php
  tests/Maker/fixtures/output/UserCrudController.php
Labels: feature

#3146 [3.0] Fixed spacing in Fields docs => Custom Options
  doc/fields.rst
Labels: doc

#3148 [3.0] Fixed JavaScript for New/Edit forms
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/new.html.twig
Labels: bug, finished

#3155 Don't define a name for the default dashboard route
  src/Controller/AbstractDashboardController.php
Labels: bug, finished

#3157 [3.0] Fixed minor typo in fields docs about TextareaField
  doc/fields.rst
Labels: doc

#3159 Added more docs for EasyAdmin 3
  doc/crud.rst
  doc/dashboards.rst
  doc/security.rst
  src/Orm/EntityPaginator.php
  src/Router/UrlBuilder.php
Labels: doc
