Repository EasyCorp/EasyAdminBundle, pull requests merged in 2020-07, with the labels that each got.

#3444 [Doc] Fixed some template paths
  doc/design.rst
Labels: doc

#3460 Fixed some type in a PhpDoc
  src/Config/UserMenu.php
Labels: bug

#3458 Update upgrade.rst
  doc/upgrade.rst
Labels: doc

#3447 Display null when an Id is null
  src/Field/Configurator/IdConfigurator.php
Labels: bug

#3462 fix(template): undefined variable error on page_footer block
  src/Resources/views/page/content.html.twig
Labels: bug

#3485 Added a way to get the locale formatted as IETF BCP 47
  src/Dto/I18nDto.php
  src/Resources/views/layout.html.twig
Labels: bug

#3474 Unnecessary quotation marks removed
  src/Resources/views/crud/action.html.twig
Labels: bug

#3473 Added missing polish translations
  src/Resources/translations/EasyAdminBundle.pl.php
Labels: feature

#3486 Fixed the wat date, time and datetime formats/patterns are handled
  src/Config/Crud.php
  src/Dto/CrudDto.php
  src/Field/Configurator/DateTimeConfigurator.php
  src/Field/DateField.php
  src/Field/DateTimeField.php
  src/Field/TimeField.php
Labels: bug

#3487 Allow to use a custom dir and namespace for generated CRUD controllers
  src/Command/MakeCrudControllerCommand.php
  src/Maker/ClassMaker.php
  src/Resources/config/services.php
Labels: feature

#3488 Added two new methods to the abstract CRUD controller
  UPGRADE.md
  src/Contracts/Controller/CrudControllerInterface.php
  src/Controller/AbstractCrudController.php
  src/Factory/FormFactory.php
Labels: feature

#3491 Allow to generate EasyAdmin URLs from outside EasyAdmin
  doc/crud.rst
  src/Registry/DashboardControllerRegistry.php
  src/Resources/config/services.php
  src/Router/CrudUrlBuilder.php
  src/Router/CrudUrlGenerator.php
Labels: feature

#3492 Fixed label functionality of Filters
  src/Dto/FilterDto.php
Labels: bug

#3512 CodeEditorField - Option lineNumbers
  assets/js/form-type-code-editor.js
  src/Field/CodeEditorField.php
  src/Resources/public/form-type-code-editor.js
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#3506 Fix html escaping for text fields
  src/Resources/views/crud/field/text.html.twig
  src/Resources/views/crud/field/textarea.html.twig
Labels: bug, finished

#3510 [3.0] Allow alpha3 codes for CountryField
  src/Field/Configurator/CountryConfigurator.php
  src/Field/CountryField.php
  src/Resources/views/crud/field/country.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: feature

#3525 Update crud.rst
  doc/crud.rst
Labels: bug, doc

#3524 Add HiddenField
  src/Field/HiddenField.php
  src/Registry/TemplateRegistry.php
  src/Resources/views/crud/field/hidden.html.twig
Labels: feature

#3529 Fixed the option to define empty labels when updating actions
  doc/actions.rst
  src/Config/Action.php
Labels: bug

#3533 Missing 'throw new ' before error message
  src/Router/CrudUrlBuilder.php
Labels: bug

#3538 litle bug
  doc/crud.rst
Labels: bug, doc, finished

#3545 Show panel icon in detail view
  src/Resources/views/crud/detail.html.twig
Labels: bug

#3548 Improved the make:admin:dashboard controller
  src/Command/MakeAdminDashboardCommand.php
Labels: bug, finished

#3546 Added a compiler pass to create the controller registries
  src/DependencyInjection/CreateControllerRegistriesPass.php
  src/EasyAdminBundle.php
  src/Registry/CrudControllerRegistry.php
  src/Registry/DashboardControllerRegistry.php
  src/Resources/config/services.php
Labels: bug

#3547 Fix unchecking / resetting filters
  src/Resources/views/crud/form_theme.html.twig
  src/Resources/views/crud/includes/_filters_modal.html.twig
Labels: bug

#3564 Add use statement for Response
  src/Resources/views/welcome.html.twig
Labels: doc

#3569 Docs Bug: Missing font-awesome attribute
  doc/dashboards.rst
Labels: doc

#3571 Add img-fluid class to the image field
  src/Resources/views/crud/field/image.html.twig
Labels: bug, design

#3576 Remove btn-line-height and change pagination-line-height
  assets/css/easyadmin-theme/variables.scss
  src/Resources/public/app.css
Labels: design

#3579 EntityFilter undefined `createAlias` method
  src/Filter/EntityFilter.php
Labels: bug

#3566 Add handling of filters to migration maker
  src/Maker/Migrator.php
  tests/Maker/fixtures/output/ProductCrudController.php
Labels: feature

#3585 Display select lists as autocomplete widgets by default
  src/Field/AssociationField.php
  src/Field/ChoiceField.php
  src/Field/Configurator/AssociationConfigurator.php
  src/Field/Configurator/ChoiceConfigurator.php
Labels: feature

#3586 Change configureActions PAGE_DETAIL reference
  doc/actions.rst
Labels: doc

#3599 Fixed some issues when generating CRUD URLs
  src/Router/CrudUrlBuilder.php
Labels: bug

#3600 Change the configurator flow
  src/Field/Configurator/MoneyConfigurator.php
Labels: bug

#3607 Fixed an issue in MoneyFields associated to null entities
  src/Field/Configurator/MoneyConfigurator.php
Labels: bug

#3606 Add script to automatically adjust textarea height
  assets/js/form-type-textarea.js
  src/Field/Configurator/TextConfigurator.php
  src/Field/TextareaField.php
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-textarea.js
  src/Resources/public/manifest.json
  webpack.config.js
Labels: feature

#3615 Remove trailing directory separator for namespace
  src/Command/MakeCrudControllerCommand.php
Labels: bug

#3614 Fixed the widget option of choice fields
  src/Field/ChoiceField.php
  src/Field/Configurator/ChoiceConfigurator.php
Labels: bug

#3619 Fixed a bug and added some tests for MoneyField configurator
  src/Field/Configurator/MoneyConfigurator.php
  tests/Field/AbstractFieldTest.php
  tests/Field/ChoiceFieldTest.php
  tests/Field/MoneyFieldTest.php
Labels: bug

#3624 Fixed the dependency injection pass that creates the services
  src/EasyAdminBundle.php
Labels: bug

#3626 Use more CSS variables in SCSS variables
  assets/css/easyadmin-theme/variables.scss
  src/Resources/public/app.css
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-textarea.js
  src/Resources/public/manifest.json
Labels: design

#3628 Add missing use in custom field example
  doc/fields.rst
Labels: doc
