Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-07, with the labels that each got.

#4445 fix #3968 and #4443 related to AdminUrlGenerator referrer generation when app is in a subdirectory
  src/Router/AdminUrlGenerator.php
Labels: bug

#4447 Fixed an issue with absolute/relative URL generation
  src/Router/AdminUrlGenerator.php
Labels: bug

#4446 Fixed some issues in file upload fields
  assets/css/easyadmin-theme/datagrids.scss
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/crud/form_theme.html.twig
Labels: bug, design

#4449 Fixed some tests and add help to commands
  src/Command/MakeAdminDashboardCommand.php
  src/Command/MakeAdminMigrationCommand.php
  src/Command/MakeCrudControllerCommand.php
  tests/DependencyInjection/CommandTest.php
Labels: bug

#4453 Resolves #4452
  src/Resources/views/symfony-form-themes/bootstrap_5_layout.html.twig
Labels: bug

#4456 Fixed the usage of label_translation_parameters in form themes
  src/Resources/views/symfony-form-themes/bootstrap_5_layout.html.twig
  src/Resources/views/symfony-form-themes/form_div_layout.html.twig
Labels: bug

#4461 Fixed #4458 -TranslationParameters
  src/Resources/views/symfony-form-themes/form_div_layout.html.twig
Labels: bug

#4459 Finish fix for #4416 (for lightbox in edit pages)
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4468 Fixed a minor design issue in autocomplete lists
  assets/css/easyadmin-theme/autocomplete.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/manifest.json
Labels: bug, design

#4470 Fix #4199 Allow editing when the file no longer exists
  src/Form/DataTransformer/StringToFileTransformer.php
Labels: bug, confirmed

#4474 Fix design of global form errors
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/crud/form_theme.html.twig
Labels: design, feature

#4472 fix(bootstrap): using bootstraps alert dismissible button
  src/Resources/views/flash_messages.html.twig
Labels: bug, design

#4473 Fix action url generation when entity DTO is missing
  src/Factory/ActionFactory.php
Labels: bug

#4480 Prevent inaccessible template being displayed with virtual/manual fields
  .gitignore
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#4475 Prevent scroll to top when user click on a lightbox link
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug, design

#4490 Fix #4489 : batchDelete error when an entity is already deleted
  src/Controller/AbstractCrudController.php
Labels: bug

#4469 [2.x] Fix PHP 8 support
  src/Twig/EasyAdminTwigExtension.php
Labels: bug

#4492 Fix some form themes that use variables not available in older Symfony versions
  src/Resources/views/symfony-form-themes/form_div_layout.html.twig
Labels: bug

#4498 Add KeyValueStore use
  doc/crud.rst
Labels: doc

#4501 Add more helper methods to show/hide form fields
  doc/fields.rst
  src/Field/FieldTrait.php
Labels: feature

#4508 missing opening form tag
  src/Resources/views/page/login.html.twig
Labels: bug

#4513 Fix the design of menu headers with icons
  assets/css/easyadmin-theme/menu.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4514 Fix a leftover method usage
  src/Factory/FieldFactory.php
Labels: bug

#4515 Fix the creation of items when collections are empty
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/datagrids.scss
  assets/css/easyadmin-theme/fields.scss
  assets/js/form-type-collection.js
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-collection.js
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4516 Fix the arguments passed to the set entity label callables
  doc/crud.rst
  src/Config/Crud.php
  src/Dto/CrudDto.php
  src/Factory/AdminContextFactory.php
Labels: bug

#4518 Fix form field columns inside form panels
  src/Resources/views/crud/form_theme.html.twig
Labels: bug, design
