Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-04, with the labels that each got.

#4283 Add chinese translation file
  .DS_Store
  src/Resources/translations/EasyAdminBundle.zh_CN.php
Labels: feature

#4281 Resolve InputBag deprecation notice
  src/Controller/AbstractCrudController.php
Labels: bug

#4294 [Doc] Removed the warning about EasyAdmin 2.x
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/design.rst
  doc/events.rst
  doc/fields.rst
  doc/filters.rst
  doc/index.rst
  doc/security.rst
  doc/upgrade.rst
Labels: doc

#4295 [Doc] Clarify where does the AdminContext argument resolver works
  doc/dashboards.rst
Labels: doc

#4297 Fixing typo
  doc/dashboards.rst
Labels: doc

#4300 Use PHP attributes in make:admin:dashboard if PHP 8 or newer is used
  src/Command/MakeAdminDashboardCommand.php
  src/Resources/skeleton/dashboard.tpl
Labels: feature

#4299 [Doc] Add PHP attributes and other formats to define routes
  doc/dashboards.rst
Labels: doc

#4298 [Doc] Improved docs about admin routes and Symfony controller integration
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
Labels: doc

#4301 Added a new NullFilter option
  doc/filters.rst
  src/Filter/Configurator/NullConfigurator.php
  src/Filter/NullFilter.php
  src/Form/Filter/Type/NullFilterType.php
  src/Resources/config/services.php
Labels: feature

#4230 Add batch actions
  assets/css/easyadmin-theme/datagrids.scss
  doc/actions.rst
  src/ArgumentResolver/BatchActionDtoResolver.php
  src/Collection/ActionCollection.php
  src/Config/Action.php
  src/Config/Actions.php
  src/Config/Option/EA.php
  src/Controller/AbstractCrudController.php
  src/Controller/AbstractDashboardController.php
  src/Dto/ActionDto.php
  src/Dto/BatchActionDto.php
  src/Factory/ActionFactory.php
  src/Factory/FormFactory.php
  src/Form/Type/CrudBatchActionFormType.php
  src/Resources/config/services.php
  src/Resources/public/app.css
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/views/crud/form_theme.html.twig
  src/Resources/views/crud/includes/_batch_action_modal.html.twig
  src/Resources/views/crud/index.html.twig
  tests/TestApplication/config/packages/framework.php
Labels: feature

#4309 Displays the filter at the correct position when search is disabled
  src/Resources/views/crud/index.html.twig
Labels: bug, design

#4316 namespace and path correction
  doc/filters.rst
Labels: doc

#4327 Update crud.rst
  doc/crud.rst
Labels: doc

#4275 Update AdminUrlGenerator usage and add a note
  doc/crud.rst
Labels: doc

#4330 Fixed the priority of the custom form themes applied in the backend
  src/Config/Crud.php
  tests/Config/CrudTest.php
Labels: bug

#4331 Fixed some CSS variable names in styles
  assets/css/easyadmin-theme/buttons.scss
  assets/css/easyadmin-theme/datagrids.scss
  assets/css/easyadmin-theme/variables.scss
  src/Resources/public/app.css
Labels: bug, design

#4332 Fixed the width of Select2 widgets in edge-cases
  assets/css/easyadmin-theme/select2.scss
  src/Resources/public/app.css
Labels: bug, design

#3975 Improve styles for user menu
  assets/css/easyadmin-theme/base.scss
Labels: design

#4203 [FIX] Orm/EntityRepository->addOrderClause()
  src/Orm/EntityRepository.php
Labels: bug

#4335 Update login form styles
  assets/css/easyadmin-theme/pages.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/page/login.html.twig
Labels: design

#4337 Fix typo for batch action documentation
  doc/actions.rst
Labels: doc

#4340 Fix the error in the batch actions documentation
  doc/actions.rst
Labels: doc
