Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-11, with the labels that each got.

#4769 Enable versioning for web assets
  src/Resources/public/app.0549744d.css
  src/Resources/public/app.0549744d.rtl.css
  src/Resources/public/app.87c1bf41.js
  src/Resources/public/app.87c1bf41.js.LICENSE.txt
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-code-editor.54afb51d.js
  src/Resources/public/form-type-code-editor.dfc63a05.css
  src/Resources/public/form-type-code-editor.dfc63a05.rtl.css
  src/Resources/public/form-type-collection.600cb76e.js
  src/Resources/public/form-type-slug.5b1774d2.js
  src/Resources/public/form-type-text-editor.3ebdf7b6.js
  src/Resources/public/form-type-text-editor.3ebdf7b6.js.LICENSE.txt
  src/Resources/public/form-type-text-editor.40b68a3d.css
  src/Resources/public/form-type-text-editor.40b68a3d.rtl.css
  src/Resources/public/form-type-textarea.23d80a2f.js
  src/Resources/public/manifest.json
  webpack.config.js
Labels: feature

#4782 Revert the versioning of web assets
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.js.LICENSE.txt
  src/Resources/public/app.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/form-type-code-editor.css
  src/Resources/public/form-type-code-editor.js
  src/Resources/public/form-type-code-editor.rtl.css
  src/Resources/public/form-type-collection.js
  src/Resources/public/form-type-slug.js
  src/Resources/public/form-type-text-editor.css
  src/Resources/public/form-type-text-editor.js
  src/Resources/public/form-type-text-editor.js.LICENSE.txt
  src/Resources/public/form-type-text-editor.rtl.css
  src/Resources/public/form-type-textarea.js
  src/Resources/public/manifest.json
  webpack.config.js
Labels: feature

#4781 Add Bahasa Indonesia (id) translation
  src/Resources/translations/EasyAdminBundle.id.php
Labels: feature

#4793 Fix datagrids top border
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4787 Make not nullable association fields required by default
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#4802 Check that the nullable key exists
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#4808 imagine_filter fail when lazy mode is enabled
  src/Twig/EasyAdminTwigExtension.php
Labels: bug

#4797 Query for symfony/uid Doctrine type "uuid" if needed
  src/Orm/EntityRepository.php
Labels: bug

#4818 Set the noopener attribute to URL menu items for security reasons
  doc/dashboards.rst
  src/Factory/MenuFactory.php
Labels: feature

#4820 fix: RTL TextEditorField
  src/Field/Configurator/TextEditorConfigurator.php
Labels: bug

#4819 fix: RTL CodeEditorField
  src/Field/Configurator/CodeEditorConfigurator.php
Labels: bug

#4794 Use the UUID regex defined in symfony/uid instead of the current regex
  src/Orm/EntityRepository.php
Labels: bug

#4828 Make EntityFilter work with uids
  src/Filter/EntityFilter.php
Labels: bug

#4803 Change the way the class parameter is loaded through embedded associations
  src/Field/Configurator/AssociationConfigurator.php
Labels: bug

#4836 Allow using Symfony 6
  composer.json
  src/ArgumentResolver/AdminContextResolver.php
  src/ArgumentResolver/BatchActionDtoResolver.php
  src/Controller/AbstractCrudController.php
  src/Controller/AbstractDashboardController.php
  src/Field/Configurator/MoneyConfigurator.php
  src/Security/SecurityVoter.php
  tests/Field/AbstractFieldTest.php
  tests/Field/ChoiceFieldTest.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: feature

#4837 Fix 8.1 regression
  src/Intl/IntlFormatter.php
Labels: bug

#4839 Test lowest dependencies; downgrade SecurityVoter::supports(); Symfony 4.4 fixes
  .github/workflows/tests-lowest-dependencies.yaml
  composer.json
  src/Security/SecurityVoter.php
  tests/Dto/CrudDtoTest.php
Labels: feature
