Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-01, with the labels that each got.

#4102 Avoid translating the form help message twice
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4100 Allow to stop the BeforeEntityDeletedEvent
  src/Controller/AbstractCrudController.php
Labels: feature

#4104 Fixed some JavaScript issues in the login form page
  src/Resources/views/page/login.html.twig
Labels: bug

#4109 [Doc] Mention the assets:install command
  doc/design.rst
Labels: doc

#4113 Add an error message when search fields are misconfigured
  src/Orm/EntityRepository.php
Labels: bug

#4134 Reorder events alphabetically
  doc/events.rst
Labels: doc

#4136 Missing menuIndex and submenuIndex URL parameters fix
  src/Factory/ActionFactory.php
Labels: bug

#4131 Update list of built-in filters in docs
  doc/filters.rst
Labels: doc

#4137 Fixed the CSS design of the sidebar
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
Labels: bug, design

#4142 Add missing HiddenField to the list
  doc/fields.rst
Labels: doc

#4138 [Fix] Inject delete form action on edit pages
  src/Resources/views/crud/edit.html.twig
Labels: bug

#4150 Inject delete form action on detail pages
  src/Resources/views/crud/detail.html.twig
Labels: bug

#4148 Add missing isPropagationStopped to BeforeEntityDeletedEvent
  src/Event/BeforeEntityDeletedEvent.php
Labels: bug

#3976 Display a gray separator line with menu sections
  src/Resources/views/layout.html.twig
Labels: design

#4156 Fix bug absolute upload dir on Windows
  src/Form/Type/FileUploadType.php
Labels: bug, confirmed

#4167 fix_4155 Use of "replace" instead of "after" to avoid an empty file n…
  src/Controller/AbstractCrudController.php
Labels: bug

#4162 Enable the use of VueJS
  src/Resources/views/crud/index.html.twig
Labels: feature
