Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-09, with the labels that each got.

#4620 Fix content resizer handler height
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4623 [BUGFIX] Remove z-index from .content-top
  assets/css/easyadmin-theme/base.scss
Labels: bug, design

#4622 Fix design of right aligned form fields with validation errors
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4621 Allow to configure HTML attributes in filter labels
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4635 fix user drop-down menu
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4639 Fix bug in default value
  src/Controller/AbstractCrudController.php
Labels: bug

#4641 Don't show the clear button in required autocomplete fields
  assets/js/autocomplete.js
  src/Resources/public/app.js
Labels: bug

#4651 Fix deprecation
  src/ArgumentResolver/BatchActionDtoResolver.php
Labels: bug

#4650 Fix #4497 - Image field - Texts & buttons updating
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4647 bug #4595 check delete-checkbox when file should be deleted
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4258 Add support for label_html FormType option
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#4624 Update TomSelect.js library
  assets/css/easyadmin-theme/autocomplete.scss
  package.json
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.rtl.css
  yarn.lock
Labels: bug, design

#4662 Allow dbal ^3.0 to be installed
  composer.json
Labels: feature

#4663 Fix collection_row data-num-items to make id unique
  assets/js/form-type-collection.js
  src/Resources/public/form-type-collection.js
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4661 Fix #4497 - Image field - additionnal display fixes
  assets/js/app.js
  src/Resources/public/app.js
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4656 Translate the autocomplete widget messages
  assets/js/autocomplete.js
  src/Resources/public/app.js
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.bg.php
  src/Resources/translations/EasyAdminBundle.ca.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.eu.php
  src/Resources/translations/EasyAdminBundle.fa.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.gl.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.it.php
  src/Resources/translations/EasyAdminBundle.lt.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.sl.php
  src/Resources/translations/EasyAdminBundle.sr_RS.php
  src/Resources/translations/EasyAdminBundle.sv.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.uk.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#4666 Update Vich delete label to match current translation keys
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4664 Fix docs about form field templates
  doc/design.rst
Labels: doc

#4665 Add table footer block
  src/Resources/views/crud/index.html.twig
Labels: feature

#4680 [2.x] Fix a return value of a method
  src/Configuration/TemplateConfigPass.php
Labels: bug

#4684 Add a disabled helper method for fields
  src/Field/FieldTrait.php
Labels: feature

#4685 Add some missing subjects to some isGranted calls in the security voter
  src/Security/SecurityVoter.php
Labels: bug

#4686 Fix CollectionConfigurator to not override some form type options
  src/Field/Configurator/CollectionConfigurator.php
Labels: bug

#4691 Fix condition in Asset::new() method
  src/Config/Asset.php
Labels: bug

#4692 Apply a default style for actions buttons/links
  doc/actions.rst
  src/Config/Action.php
  src/Factory/ActionFactory.php
Labels: bug, design

#4694 [Doc] Improve the docs about form panels
  doc/fields.rst
Labels: doc

#4688 Fixes #4679 - The cancel button in batch action modal does not work.
  assets/js/app.js
  src/Resources/public/app.js
  src/Resources/views/crud/includes/_batch_action_modal.html.twig
  src/Resources/views/crud/includes/_delete_form.html.twig
  src/Resources/views/crud/includes/_filters_modal.html.twig
Labels: bug

#4695 Don't allow to remove contents of disabled choice fields
  assets/js/autocomplete.js
  src/Resources/public/app.js
Labels: bug

#4696 Improve the default behavior of code/text editors in index/detail pages
  src/Resources/views/crud/field/code_editor.html.twig
  src/Resources/views/crud/field/text_editor.html.twig
Labels: bug

#4697 Improve the pagination when there are hidden results
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/paginator.html.twig
Labels: feature

#4703 [Doc] Minor update about setTextAlign() method
  doc/fields.rst
Labels: doc

#4704 Improve the behavior of the setFormTypeOptions() method
  doc/fields.rst
  src/Dto/FieldDto.php
Labels: bug

#4706 Adding full path to `variables.scss`
  doc/design.rst
Labels: doc

#4712 Add a Twig block to override empty table body
  src/Resources/views/crud/index.html.twig
Labels: feature, design

#4709 Update ajaxEdit visility
  src/Controller/AbstractCrudController.php
Labels: feature

#4682 Allow deep linking of associations
  src/Factory/EntityFactory.php
  src/Field/Configurator/AssociationConfigurator.php
Labels: feature
