Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-12, with the labels that each got.

#4851 Fix collection delete button
  assets/js/form-type-collection.js
Labels: bug

#4783 Respect filters while searching, add additional search event
  src/Event/AfterEntitySearchEvent.php
  src/Orm/EntityRepository.php
  src/Resources/config/services.php
  src/Resources/views/layout.html.twig
Labels: feature

#4866 Add missing catalan translations
  src/Resources/translations/EasyAdminBundle.ca.php
Labels: feature

#4867 fix delete file
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4869 Tweak form tab design
  assets/css/easyadmin-theme/forms.scss
  assets/css/easyadmin-theme/variables-theme.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: design

#4872 Fix for PR : Tweak form tab design #4869
  assets/css/easyadmin-theme/forms.scss
  assets/css/easyadmin-theme/variables-theme.scss
  src/Dto/FieldDto.php
  src/Field/FormField.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug

#4870 keep sort query parameter
  src/Factory/ActionFactory.php
Labels: feature

#4885 Fix an issue with iterable filters (searching with filters)
  src/Resources/views/layout.html.twig
Labels: bug

#4898 Restore the 'doctrine' service in AbstractController
  src/Controller/AbstractCrudController.php
Labels: bug

#4902 Fix PHP 8.1 deprecation about nullable argument
  src/Config/MenuItem.php
Labels: bug

#4901 Fix some types in FlattenException class methods
  src/Exception/FlattenException.php
Labels: bug

#4905 Backport some fixes for PHP 8.1 deprecations
  src/Collection/ActionCollection.php
  src/Collection/EntityCollection.php
  src/Dto/SearchDto.php
  src/Factory/ActionFactory.php
  src/Field/Configurator/UrlConfigurator.php
Labels: bug

#4910 Fix some issues related to filters
  src/Field/Configurator/CommonPreConfigurator.php
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4927 Fix for InvalidArgumentException when field property contains square brackets
  src/Form/Type/CrudFormType.php
Labels: bug

#4931 [Doc] Add a tip about reordering and offsetting fields
  doc/fields.rst
Labels: doc

#4932 Removed some unused styles
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/variables-bootstrap.scss
  assets/css/easyadmin-theme/variables-theme.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/images/flags/GP.png
  src/Resources/public/images/flags/MQ.png
  src/Resources/public/manifest.json
Labels: design
