Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-05, with the labels that each got.

#4348 Fix doc typo
  doc/actions.rst
Labels: doc

#4347 Doc: Add missing Symfony Response use statements
  doc/dashboards.rst
Labels: doc

#4343 Fix return type for getFormType
  src/Dto/FilterDto.php
Labels: feature

#4344 Fix for #4306
  src/Filter/EntityFilter.php
Labels: bug

#4356 Include _filters_modal.html.twig only once
  src/Resources/views/crud/includes/_filters_modal.html.twig
  src/Resources/views/crud/index.html.twig
Labels: bug

#4359 Fixed conversion of EntityDto to string in batch delete
  src/Controller/AbstractCrudController.php
  src/Dto/EntityDto.php
Labels: bug

#4363 Fixed issues with out of range paginators
  src/Controller/AbstractCrudController.php
  src/Orm/EntityPaginator.php
Labels: bug

#4364 Load JavaScript files in page head instead of body
  UPGRADE.md
  doc/design.rst
  src/Resources/views/layout.html.twig
Labels: bug

#4375 Do not render the dropdown-button when there are no actions
  src/Resources/views/crud/index.html.twig
Labels: bug, design

#4373 fix action name on batch action
  src/Resources/views/crud/index.html.twig
Labels: bug

#4381 Don't display empty labels in collection items
  assets/css/easyadmin-theme/fields.scss
  src/Resources/public/app.css
Labels: bug, design

#4384 fix get field dto on filter clause
  src/Orm/EntityRepository.php
Labels: bug

#4396 Fixed the JavaScript code of some form fields
  assets/js/form-type-code-editor.js
  assets/js/form-type-slug.js
  assets/js/form-type-textarea.js
  src/Resources/public/form-type-code-editor.js
  src/Resources/public/form-type-slug.js
Labels: bug

#4397 Fix ImageField template for multiple images
  src/Resources/views/crud/field/image.html.twig
Labels: bug, design

#4390 Action permission is also checked with the entity instance
  src/Controller/AbstractCrudController.php
  src/Factory/ActionFactory.php
  src/Security/SecurityVoter.php
Labels: feature

#4400 Allow to configure properties and HTML attributes for assets
  UPGRADE.md
  doc/design.rst
  src/Config/Asset.php
  src/Config/Assets.php
  src/Dto/AssetDto.php
  src/Dto/AssetsDto.php
  src/Dto/FieldDto.php
  src/Field/Configurator/CodeEditorConfigurator.php
  src/Field/Configurator/TextEditorConfigurator.php
  src/Field/FieldTrait.php
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/new.html.twig
  src/Resources/views/includes/_css_assets.html.twig
  src/Resources/views/includes/_encore_link_tags.html.twig
  src/Resources/views/includes/_encore_script_tags.html.twig
  src/Resources/views/includes/_js_assets.html.twig
  src/Resources/views/layout.html.twig
Labels: feature

#4405 Fixed "batch delete" action
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4404 Fixed the injection of service in CRUD controller actions
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#4413 Fixed the URL generation when using multiple dashboards
  src/Router/AdminUrlGenerator.php
Labels: bug

#4409 Fixed the translation of flash messages
  src/Resources/views/flash_messages.html.twig
Labels: bug

#4417 Fix #4416 (Lightbox is not working)
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4421 fix: multiples batch actions
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4410 Updated the way text contents with HTML tags are displayed
  UPGRADE.md
  src/Field/Configurator/TextConfigurator.php
  src/Field/TextField.php
  src/Field/TextareaField.php
  src/Resources/views/crud/field/text.html.twig
Labels: feature

#4423 Fixed the translation of form field help in custom forms
  src/Resources/views/crud/form_theme.html.twig
Labels: bug
