Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-08, with the labels that each got.

#4520 Fixed modals close button
  src/Resources/views/crud/field/code_editor.html.twig
  src/Resources/views/crud/field/text_editor.html.twig
Labels: bug, design

#4522 Update front-end deps
  assets/css/easyadmin-theme/variables-bootstrap.scss
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.js.LICENSE.txt
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-code-editor.js
  src/Resources/public/form-type-slug.js
  yarn.lock
Labels: design

#4523 Deprecate some Twig blocks instead of removing them
  UPGRADE.md
  src/Resources/views/page/content.html.twig
Labels: design

#4530 Remove form rows from index and detail pages
  src/Factory/FieldFactory.php
Labels: bug, design

#4525 Added missing `--form-bg` variable
  assets/css/easyadmin-theme/variables-theme.scss
Labels: bug, design

#4531 Fix the setColumns method usage when using automatic fields
  src/Dto/FieldDto.php
Labels: bug

#4527 Target wrapper element if icon clicked on batch action button
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4535 Misc design tweaks
  assets/css/easyadmin-theme/base.scss
  src/Dto/FieldDto.php
  src/Field/Configurator/ChoiceConfigurator.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  tests/Field/ChoiceFieldTest.php
Labels: design

#4540 fixed typo spl_object_hash in twig extension
  src/Twig/EasyAdminTwigExtension.php
Labels: bug

#4536 Do not access primary key on new form
  src/Field/Configurator/BooleanConfigurator.php
Labels: bug

#4542 Make header sticky again in edit and new pages
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: design, feature

#4546 Allow to display all collection items expanded by default
  src/Field/CollectionField.php
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#4548 Fix modal zIndex for be on top of the top bar
  assets/css/easyadmin-theme/variables-bootstrap.scss
Labels: bug, design

#4550 Fix infinite loop
  src/Resources/views/page/content.html.twig
Labels: bug

#4553 Import the entire Bootstrap JS components
  assets/js/app.js
  src/Resources/public/app.js
Labels: feature

#4554 Hide the empty search section in responsive mode
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/layout.html.twig
Labels: bug, design

#4555 Fix boolean switches in responsive design
  assets/css/easyadmin-theme/datagrids.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4557 Make Collection form type template more robust
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4556 Improve the design of the form collections
  assets/css/easyadmin-theme/fields.scss
  assets/js/form-type-collection.js
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-collection.js
  src/Resources/views/crud/form_theme.html.twig
Labels: bug, design

#4560 support Ulid search
  src/Orm/EntityRepository.php
Labels: feature

#4566 Login page improve
  src/Resources/views/page/login.html.twig
Labels: design

#4567 Fixed the design of flash messages
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4568 Add the full Tailwind CSS color palette
  assets/css/easyadmin-theme/color-palette.scss
  assets/css/easyadmin-theme/variables-theme.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: feature, design

#4569 Fix Tooltip and Popover
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4576 Fix: Multiple calls of $actions->disable will overwrite the previous call
  src/Dto/ActionConfigDto.php
Labels: bug

#4582 Check for ea variable when rendering flash messages
  src/Resources/views/flash_messages.html.twig
Labels: bug

#4581 Update actions.rst
  doc/actions.rst
Labels: doc

#4585 minor responsivity improvements
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/datagrids.scss
Labels: bug, design

#4583 Fix some issues with HTML tags in the detail page
  src/Resources/views/crud/detail.html.twig
Labels: bug

#4587 [CSS] Minor fix to dropdown headers
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4598 Use css var for red-100
  assets/css/easyadmin-theme/forms.scss
Labels: bug, design

#4610 Add parameters to display a "remember me" checkbox on login page
  doc/dashboards.rst
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.bg.php
  src/Resources/translations/EasyAdminBundle.ca.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.eu.php
  src/Resources/translations/EasyAdminBundle.fa.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.gl.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.it.php
  src/Resources/translations/EasyAdminBundle.lt.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.sl.php
  src/Resources/translations/EasyAdminBundle.sr_RS.php
  src/Resources/translations/EasyAdminBundle.sv.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.uk.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
  src/Resources/views/page/login.html.twig
Labels: feature

#4615 Fix unexpected classes in form theme
  src/Resources/views/crud/form_theme.html.twig
Labels: bug, design
