Repository EasyCorp/EasyAdminBundle, pull requests merged in 2021-02, with the labels that each got.

#4172 [docs/crud] Minor sentence correction
  doc/crud.rst
Labels: doc

#4171 Improved paginator to display page numbers
  assets/css/easyadmin-theme/base.scss
  doc/crud.rst
  src/Config/Crud.php
  src/Dto/PaginatorDto.php
  src/Orm/EntityPaginator.php
  src/Resources/public/app.css
  src/Resources/views/crud/paginator.html.twig
Labels: feature

#4182 Add return type
  doc/actions.rst
Labels: doc

#4184 Use "var(--body-bg)" variable for body bg color in Bootstrap
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
Labels: bug, design

#4186 Allow to render the same field more than once in index/detail pages
  src/Collection/FieldCollection.php
  src/Dto/FieldDto.php
  src/Resources/views/crud/detail.html.twig
Labels: feature

#4196 Fixed the handling of label callables
  src/Dto/CrudDto.php
  tests/Dto/CrudDtoTest.php
Labels: bug

#4206 Fixed the automatic field configuration
  src/Collection/FieldCollection.php
  src/Controller/AbstractCrudController.php
  src/Factory/FieldFactory.php
Labels: bug

#4212 Fixed duplication of fields
  src/Dto/FieldDto.php
  src/Factory/FieldFactory.php
Labels: bug

#4214 Fixes the behavior of boolean switches
  src/Collection/FieldCollection.php
  src/Dto/FieldDto.php
  src/Factory/FieldFactory.php
Labels: bug

#4216 Fix to make setFieldFqcn() work in configureFields of entity CrudController
  src/Collection/FieldCollection.php
  src/Dto/FieldDto.php
Labels: bug

#4219 Modify ellipsis in pager
  src/Resources/views/crud/paginator.html.twig
Labels: design

#4217 Fixed a design issue in menus with short labels
  assets/css/easyadmin-theme/menu.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#4221 Fix #4188
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#4223 Add support for loading Webpack Encore entries
  doc/design.rst
  doc/fields.rst
  src/Config/Assets.php
  src/Dto/AssetsDto.php
  src/Dto/FieldDto.php
  src/Field/FieldTrait.php
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/new.html.twig
  src/Resources/views/layout.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: feature
