Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-09, with the labels that each got.

#5352 [3.x branch] custom action permissions are respected.
  src/Config/Actions.php
  src/Dto/ActionConfigDto.php
  src/Factory/AdminContextFactory.php
  tests/Controller/CategoryCrudControllerTest.php
  tests/Controller/DashboardControllerTest.php
  tests/TestApplication/config/packages/security.php
  tests/TestApplication/src/Config/Action.php
  tests/TestApplication/src/Controller/CategoryCrudController.php
  tests/TestApplication/src/Controller/SecureDashboardController.php
  tests/TestApplication/src/Entity/Category.php
Labels: bug

#5401 fix doc typo
  doc/fields/CollectionField.rst
Labels: doc

#5374 Fix grouped choices in ChoiceFields
  src/Field/Configurator/ChoiceConfigurator.php
  tests/Field/ChoiceFieldTest.php
Labels: bug

#5415 Example code update because of deprecations
  doc/actions.rst
Labels: doc

#5380 fix #5379
  assets/css/easyadmin-theme/forms.scss
Labels: bug, design

#5154 Add setEmptyData method to FieldTrait
  src/Field/FieldTrait.php
Labels: feature

#5351 Fix: keep existing formatted value
  src/Field/Configurator/CommonPreConfigurator.php
  tests/Field/AbstractFieldTest.php
  tests/Field/Configurator/CommonPreConfiguratorTest.php
Labels: bug
