Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-03, with the labels that each got.

#5082 Fix some issues in dark mode design
  assets/css/easyadmin-theme/datagrids.scss
  assets/css/easyadmin-theme/forms.scss
  assets/css/easyadmin-theme/variables-theme.scss
  assets/css/form-type-code-editor.css
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-code-editor.css
  src/Resources/public/form-type-code-editor.rtl.css
  src/Resources/views/crud/index.html.twig
Labels: bug, design

#5079 Add optional autofocus to search input on index pages
  doc/crud.rst
  src/Config/Crud.php
  src/Dto/CrudDto.php
  src/Resources/views/layout.html.twig
Labels: feature

#5087 Improve Bulgarian translation
  src/Resources/translations/EasyAdminBundle.bg.php
Labels: feature

#5046 fix: issue #5038 datetimefilter array to string conversion error
  src/Resources/views/layout.html.twig
Labels: bug

#5089 Improve the help content of CRUD pages
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/variables-bootstrap.scss
  assets/css/easyadmin-theme/variables-theme.scss
  assets/js/app.js
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.rtl.css
  src/Resources/views/layout.html.twig
Labels: design

#5094 Fix AL flag
  assets/images/flags/AL.png
Labels: bug, design

#5102 Satisfy PHP CS Fixer
  src/Config/Action.php
  src/Config/Crud.php
  src/Config/Menu/CrudMenuItem.php
  src/Config/Menu/MenuItemTrait.php
  src/Dto/ActionDto.php
  src/Dto/CrudDto.php
  src/Dto/DashboardDto.php
  src/Dto/EntityDto.php
  src/Dto/FieldDto.php
  src/Dto/FilterConfigDto.php
  src/Dto/FilterDto.php
  src/Event/AbstractLifecycleEvent.php
Labels: bug

#5103 Fix tests by skipping one dataset on MacOS
  tests/Intl/IntlFormatterTest.php
Labels: bug

#5100 Update actions.rst
  doc/actions.rst
Labels: bug, doc

#5097 Fix bug of date field toggling
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5105 Add docs and improve error message for custom mapping types
  doc/fields.rst
  src/Factory/FieldFactory.php
Labels: doc

#4971 Allow to customize the referrer of admin URLs
  src/Router/AdminUrlGenerator.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: feature

#5122 Fix some styles in dark mode
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/variables-theme.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#5118 Fix issue #5114 : Update documentation about AssociationField
  doc/fields/AssociationField.rst
Labels: doc

#5125 Fix height for multiple select
  assets/css/easyadmin-theme/forms.scss
Labels: bug, design

#5141 Font awesome 6
  assets/css/app.scss
  doc/actions.rst
  doc/dashboards.rst
  package.json
  src/Config/Action.php
  src/Config/MenuItem.php
  src/Field/FormField.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/fonts/fa-brands-400.2285773e.woff
  src/Resources/public/fonts/fa-brands-400.2285773e6b4b172f07d9b777c81b0775.woff
  src/Resources/public/fonts/fa-brands-400.23f19bb0.eot
  src/Resources/public/fonts/fa-brands-400.23f19bb08961f37aaf692ff943823453.eot
  src/Resources/public/fonts/fa-brands-400.2f517e09eb2ca6650ff5bec5a95157ab.svg
  src/Resources/public/fonts/fa-brands-400.527940b1.ttf
  src/Resources/public/fonts/fa-brands-400.527940b104eb2ea366c8630f3f038603.ttf
  src/Resources/public/fonts/fa-brands-400.b823fc0d.ttf
  src/Resources/public/fonts/fa-brands-400.b823fc0dbb5a5f0c21bbcc2a268f92aa.ttf
  src/Resources/public/fonts/fa-brands-400.d878b0a6.woff2
  src/Resources/public/fonts/fa-brands-400.d878b0a6a1144760244ff0665888404c.woff2
  src/Resources/public/fonts/fa-brands-400.ebb7a127.woff2
  src/Resources/public/fonts/fa-brands-400.ebb7a127d2d8ee6f183274b7557718ab.woff2
  src/Resources/public/fonts/fa-regular-400.0caf4c6c.woff2
  src/Resources/public/fonts/fa-regular-400.0caf4c6cf244a90efcc5bf6d4e5578c1.woff2
  src/Resources/public/fonts/fa-regular-400.0d03b1bb.ttf
  src/Resources/public/fonts/fa-regular-400.0d03b1bbd1d62c1e128489eb2d4fb85d.ttf
  src/Resources/public/fonts/fa-regular-400.4689f52cc96215721344e51e5831eec1.svg
  src/Resources/public/fonts/fa-regular-400.491974d1.ttf
  src/Resources/public/fonts/fa-regular-400.491974d108fe4002b2aaf7ffc48249a0.ttf
  src/Resources/public/fonts/fa-regular-400.77206a6b.eot
  src/Resources/public/fonts/fa-regular-400.77206a6bb316fa0aded5083cc57f92b9.eot
  src/Resources/public/fonts/fa-regular-400.7a333762.woff2
  src/Resources/public/fonts/fa-regular-400.7a3337626410ca2f40718481c755640f.woff2
  src/Resources/public/fonts/fa-regular-400.bb58e57c.woff
  src/Resources/public/fonts/fa-regular-400.bb58e57c48a3e911f15fa834ff00d44a.woff
  src/Resources/public/fonts/fa-solid-900.1551f4f6.woff2
  src/Resources/public/fonts/fa-solid-900.1551f4f60c37af51121f106501f69b80.woff2
  src/Resources/public/fonts/fa-solid-900.59edf72a.woff2
  src/Resources/public/fonts/fa-solid-900.59edf72a325ac2048d6077f64773674f.woff2
  src/Resources/public/fonts/fa-solid-900.7a8b4f130182d19a2d7c67d80c090397.svg
  src/Resources/public/fonts/fa-solid-900.9bbb245e.eot
  src/Resources/public/fonts/fa-solid-900.9bbb245e67a133f6e486d8d2545e14a5.eot
  src/Resources/public/fonts/fa-solid-900.be9ee23c.ttf
  src/Resources/public/fonts/fa-solid-900.be9ee23c0c6390141475d519c2c5fb8f.ttf
  src/Resources/public/fonts/fa-solid-900.e615bbcb.ttf
  src/Resources/public/fonts/fa-solid-900.e615bbcb258550973c165dfc0d871c96.ttf
  src/Resources/public/fonts/fa-solid-900.eeccf4f6.woff
  src/Resources/public/fonts/fa-solid-900.eeccf4f66002c6f2ba24d3d22f2434c2.woff
  src/Resources/public/fonts/fa-v4compatibility.4baccb54.ttf
  src/Resources/public/fonts/fa-v4compatibility.4baccb548138840fa33a2004ea6572e9.ttf
  src/Resources/public/fonts/fa-v4compatibility.afac8956.woff2
  src/Resources/public/fonts/fa-v4compatibility.afac89562a53014590692a199d237a09.woff2
  src/Resources/public/images/fa-brands-400.2f517e09.svg
  src/Resources/public/images/fa-regular-400.4689f52c.svg
  src/Resources/public/images/fa-solid-900.7a8b4f13.svg
  src/Resources/public/manifest.json
  yarn.lock
Labels: feature, design
