Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-06, with the labels that each got.

#5210 Use CRUD form in CollectionField
  doc/fields/CollectionField.rst
  src/Field/CollectionField.php
  src/Field/Configurator/CollectionConfigurator.php
  src/Resources/config/services.php
Labels: feature, priority: important

#5269 [Docs] Incorrect method call 'useEntryCrudForm'
  doc/fields/CollectionField.rst
Labels: doc

#5019 Fix custom action permissions
  src/Config/Actions.php
  src/Dto/ActionConfigDto.php
  src/Factory/AdminContextFactory.php
  tests/Controller/CategoryCrudControllerTest.php
  tests/TestApplication/config/packages/security.php
  tests/TestApplication/src/Config/Action.php
  tests/TestApplication/src/Controller/CategoryCrudController.php
Labels: bug

#5277 Allow using HTML tags in action labels
  src/Resources/views/crud/action.html.twig
Labels: feature

#5282 escape backslash in constants function
  src/Resources/views/page/login.html.twig
  src/Resources/views/page/login_minimal.html.twig
Labels: bug

#5288 Fix assets for applications served under subdirectories
  src/Resources/bin/fix-assets-manifest-file.php
  src/Resources/public/app.92323293.css
  src/Resources/public/app.92323293.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  webpack.config.js
Labels: bug

#5297 Fix again the handling of versioned assets
  src/Asset/AssetPackage.php
  src/Resources/bin/fix-assets-manifest-file.php
  src/Resources/config/services.php
  src/Resources/public/app.34c6b3bb.css
  src/Resources/public/app.34c6b3bb.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  webpack.config.js
Labels: bug

#5300 Fix panel help translation
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5308 Allow to add form themes from fields
  doc/fields.rst
  src/Config/Crud.php
  src/Dto/CrudDto.php
  src/Dto/FieldDto.php
  src/Factory/FieldFactory.php
  src/Field/FieldTrait.php
Labels: feature
