Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-01, with the labels that each got.

#4937 Fix the setNumberFormat() method and allow to override it in numeric fields
  doc/crud.rst
  src/Field/Configurator/IntegerConfigurator.php
  src/Field/Configurator/NumberConfigurator.php
  src/Field/IntegerField.php
  src/Field/NumberField.php
  src/Resources/config/services.php
Labels: bug

#4940 add entity vars for dropdown item action
  src/Resources/views/crud/index.html.twig
Labels: feature

#4943 [Docs] Updating paths to variable files
  doc/design.rst
Labels: doc

#4951 Fixing Symfony 6 support in DynamicChoiceLoader - for ArrayFilter
  src/Form/ChoiceList/Loader/DynamicChoiceLoader.php
Labels: bug

#4953 Allow to render badges in menu items
  assets/css/easyadmin-theme/badges.scss
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/menu.scss
  assets/css/easyadmin-theme/variables-theme.scss
  doc/dashboards.rst
  src/Config/Menu/MenuItemTrait.php
  src/Dto/MenuItemBadgeDto.php
  src/Dto/MenuItemDto.php
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/views/menu.html.twig
Labels: feature

#4954 Handle VichUploaderBundle download_label in form theme
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4979 Provide Bootstrap variable to custom backend pages
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4972 Allow to filter the list of countries displayed in Country field
  src/Field/Configurator/CountryConfigurator.php
  src/Field/CountryField.php
Labels: feature

#4981 Change HTTP verb to fulfill standard
  assets/js/app.js
  src/Resources/public/app.js
Labels: bug

#4973 Allow to load assets conditionally based on page (both for CRUDs and fields)
  doc/design.rst
  doc/fields.rst
  src/Config/Asset.php
  src/Controller/AbstractCrudController.php
  src/Dto/AssetDto.php
  src/Dto/AssetsDto.php
  src/Dto/CrudDto.php
  src/Factory/AdminContextFactory.php
  src/Field/ArrayField.php
  src/Field/CodeEditorField.php
  src/Field/CollectionField.php
  src/Field/SlugField.php
  src/Field/TextEditorField.php
  src/Field/TextareaField.php
  src/Form/Type/CrudFormType.php
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/new.html.twig
Labels: feature

#4987 Direct link to FontAwesome icons
  doc/actions.rst
  doc/dashboards.rst
Labels: doc

#4974 Fixed statement about dropdown actions default
  doc/actions.rst
Labels: bug, doc

#4991 [Doc] Better explain the mapping between Doctrine types and EasyAdmin types
  doc/fields.rst
Labels: doc

#4993 Removed strange padding-right
  assets/css/easyadmin-theme/datagrids.scss
Labels: design

#4995 Wrapped the action label (NOT icon) in a span
  src/Resources/views/crud/action.html.twig
Labels: design

#5005 [Doc] Add more docs for fields
  doc/crud.rst
  doc/fields/ArrayField.rst
  doc/fields/AssociationField.rst
  doc/fields/AvatarField.rst
  doc/fields/BooleanField.rst
  doc/fields/ChoiceField.rst
  doc/fields/CodeEditorField.rst
  doc/fields/CollectionField.rst
  doc/fields/ColorField.rst
  doc/fields/CountryField.rst
  doc/fields/CurrencyField.rst
  doc/fields/DateField.rst
  doc/fields/DateTimeField.rst
  doc/fields/EmailField.rst
  doc/fields/HiddenField.rst
  doc/fields/IdField.rst
  doc/fields/ImageField.rst
  doc/fields/IntegerField.rst
  doc/fields/LanguageField.rst
  doc/fields/LocaleField.rst
  doc/fields/MoneyField.rst
  doc/fields/NumberField.rst
  doc/fields/PercentField.rst
  doc/fields/SlugField.rst
  doc/fields/TelephoneField.rst
  doc/fields/TextEditorField.rst
  doc/fields/TextField.rst
  doc/fields/TextareaField.rst
  doc/fields/TimeField.rst
  doc/fields/TimezoneField.rst
  doc/fields/UrlField.rst
Labels: doc

#4985 Fix text editor validation
  assets/js/form-type-text-editor.js
  src/Resources/public/form-type-text-editor.js
Labels: bug, priority: important
