Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-04, with the labels that each got.

#5146 Allow to disable the dark mode design
  assets/js/page-color-scheme.js
  doc/dashboards.rst
  src/Config/Dashboard.php
  src/Context/AdminContext.php
  src/Dto/DashboardDto.php
  src/Resources/public/page-color-scheme.js
  src/Resources/views/layout.html.twig
Labels: feature, design

#5152 [BUGFIX] Do not translate already translated tab label
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5084 Deprecate URL signatures and remove them by default
  UPGRADE.md
  doc/.doctor-rst.yaml
  doc/crud.rst
  doc/dashboards.rst
  doc/design.rst
  src/Config/Dashboard.php
  src/Dto/DashboardDto.php
  src/EventListener/AdminRouterSubscriber.php
  src/Resources/config/services.php
  src/Resources/views/layout.html.twig
  src/Router/AdminUrlGenerator.php
  src/Router/UrlSigner.php
  tests/Router/AdminUrlGeneratorTest.php
  tests/Router/UrlSignerTest.php
Labels: feature

#5075 Fix collection entry form
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5160 Fix "browse" button for regular file inputs in dark mode
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#5172 Fix some button styles
  assets/css/easyadmin-theme/buttons.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#5174 Fixes and updates for front-end dependencies
  package.json
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
  src/Resources/public/field-code-editor.css
  src/Resources/public/field-code-editor.rtl.css
  src/Resources/public/field-text-editor.css
  src/Resources/public/field-text-editor.rtl.css
  src/Resources/public/manifest.json
  webpack.config.js
  yarn.lock
Labels: bug, design

#5176 fix(form_theme): regression missing default value.
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5181 Allow to configure Trix editor via text editor fields
  assets/js/field-text-editor.js
  doc/fields/TextEditorField.rst
  src/Field/TextEditorField.php
  src/Resources/public/field-text-editor.js
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#5184 Escape the contents of the default title pages
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/new.html.twig
Labels: bug

#5186 Fix some CSS styles for FontAwesome 6 icons
  assets/css/easyadmin-theme/base.scss
  src/Resources/public/app.css
  src/Resources/public/app.rtl.css
Labels: bug, design

#5188 docs: fixes typo on setUploadDir example for ImageField docs
  doc/fields/ImageField.rst
Labels: doc

#5187 Add includeOnly and remove to Language and Locale field types
  doc/fields/LanguageField.rst
  doc/fields/LocaleField.rst
  src/Field/Configurator/LanguageConfigurator.php
  src/Field/Configurator/LocaleConfigurator.php
  src/Field/LanguageField.php
  src/Field/LocaleField.php
Labels: feature

#5200 Allow running script tags included in collection prototypes
  assets/js/field-collection.js
Labels: bug

#5204 set only background-color in form-select and form-widget
  assets/css/easyadmin-theme/forms.scss
Labels: bug, design
