Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-05, with the labels that each got.

#5214 UrlSigner deprecation improvement
  src/Router/UrlSigner.php
Labels: bug

#5226 Added Hebrew translation
  src/Resources/translations/EasyAdminBundle.he.php
Labels: feature

#5222 Add default keyword to variables-bootstrap.scss variables
  assets/css/easyadmin-theme/variables-bootstrap.scss
Labels: bug, design

#5229 Fix a minor issue in CurrencyField configurator
  src/Field/Configurator/CurrencyConfigurator.php
Labels: bug

#5230 Fix a return value type issue
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#5231 [Bug] Fixing tomselect over-filtering Ajax autocomplete results
  assets/js/autocomplete.js
Labels: bug

#5239 Fix the select tag design in dark mode
  assets/css/easyadmin-theme/forms.scss
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.rtl.css
Labels: bug, design

#5234 Allow to configure the favicon of the login page
  doc/dashboards.rst
  src/Resources/views/page/login.html.twig
  src/Resources/views/page/login_minimal.html.twig
Labels: feature

#5243 Fix responsive appearance menu
  src/Resources/views/layout.html.twig
Labels: bug, design

#5249 Fix issue #5240 - entity placeholders ignored for Crud::PAGE_NEW titles
  src/Resources/views/crud/new.html.twig
Labels: bug

#5253 translate help messages
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/layout.html.twig
Labels: bug, status: confirmed

#5251 Use correct method to get fieldDto
  src/Factory/FilterFactory.php
Labels: bug
