Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-10, with the labels that each got.

#5443 Fix: Fixes search with custom Ulid & Uuid classes
  src/Orm/EntityRepository.php
Labels: bug

#5441 Added possibility to select multiple entities in the filter
  src/Filter/EntityFilter.php
Labels: feature

#5447 Fix: Updated alignement in sidebar items
  assets/css/easyadmin-theme/menu.scss
Labels: bug, design

#5458 Fix: Search
  src/Orm/EntityRepository.php
Labels: bug
