Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-02, with the labels that each got.

#5021 Remove filtering for head/body contents
  src/Dto/AssetsDto.php
Labels: bug

#5032 Fix typed property which can be a callable
  src/Dto/ActionDto.php
Labels: bug

#5030 [Doc] Add the docs for the remaining fields
  doc/fields/ArrayField.rst
  doc/fields/AssociationField.rst
  doc/fields/AvatarField.rst
  doc/fields/BooleanField.rst
  doc/fields/ChoiceField.rst
  doc/fields/CodeEditorField.rst
  doc/fields/CollectionField.rst
  doc/fields/ColorField.rst
  doc/fields/EmailField.rst
  doc/fields/HiddenField.rst
  doc/fields/ImageField.rst
  doc/fields/IntegerField.rst
  doc/fields/MoneyField.rst
  doc/fields/NumberField.rst
  doc/fields/PercentField.rst
  doc/fields/SlugField.rst
  doc/fields/TextEditorField.rst
  doc/fields/TextField.rst
  doc/fields/TextareaField.rst
  doc/fields/UrlField.rst
  doc/images/fields/field-choice-autocomplete-options.png
  doc/images/fields/field-choice-autocomplete.png
  doc/images/fields/field-language.png
  src/Field/ChoiceField.php
Labels: doc

#5041 On AJAX toggle check method and add CSRF token
  src/Controller/AbstractCrudController.php
  src/Field/Configurator/BooleanConfigurator.php
  src/Resources/config/services.php
  tests/Controller/ToggleTest.php
  tests/TestApplication/src/Controller/CategoryCrudController.php
  tests/TestApplication/src/Entity/Category.php
Labels: bug

#5053 Fix deprecations
  src/Dto/ActionDto.php
  src/Dto/CrudDto.php
Labels: bug

#5055 Allow selecting multiple rows holding shift key in index view
  assets/css/easyadmin-theme/datagrids.scss
  assets/js/app.js
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-code-editor.js
  src/Resources/public/form-type-slug.js
  src/Resources/public/form-type-textarea.js
  src/Resources/public/images/flags/AL.png
Labels: feature

#5063 Add a new dark mode design
  assets/css/easyadmin-theme/autocomplete.scss
  assets/css/easyadmin-theme/badges.scss
  assets/css/easyadmin-theme/base.scss
  assets/css/easyadmin-theme/buttons.scss
  assets/css/easyadmin-theme/datagrids.scss
  assets/css/easyadmin-theme/fields.scss
  assets/css/easyadmin-theme/forms.scss
  assets/css/easyadmin-theme/switches.scss
  assets/css/easyadmin-theme/variables-theme.scss
  assets/css/form-type-text-editor.css
  assets/js/app.js
  src/Config/Actions.php
  src/Resources/public/app.css
  src/Resources/public/app.js
  src/Resources/public/app.rtl.css
  src/Resources/public/form-type-text-editor.css
  src/Resources/public/form-type-text-editor.rtl.css
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.id.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
  src/Resources/views/crud/form_theme.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/layout.html.twig
Labels: feature, design

#5068 Fix showing paginator when entity needs permission
  src/Resources/views/crud/index.html.twig
Labels: bug

#5065 Readd leave empty checkbox for dates and times
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#5069 [Doc] Removed extra quote
  doc/design.rst
Labels: doc

#5072 Add a custom Twig function to handle CSRF token generation in templates
  src/Resources/config/services.php
  src/Resources/views/crud/includes/_delete_form.html.twig
  src/Twig/EasyAdminTwigExtension.php
Labels: bug

#5073 [Doc] Respect `setChoices()` arguments
  doc/fields/ChoiceField.rst
Labels: doc
