Repository EasyCorp/EasyAdminBundle, pull requests merged in 2022-12, with the labels that each got.

#5503 Inject router service instead of router.default
  src/Resources/config/services.php
Labels: bug

#5486 Fix an issue when using Symfony form data transformers
  src/Dto/EntityDto.php
Labels: bug, help wanted, priority: important

#5501 slug field multiple target name
  assets/js/field-slug.js
  src/Field/SlugField.php
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#5521 Add some new methods to the paginator to get the range result numbers
  src/Orm/EntityPaginator.php
Labels: feature

#5525 Fix the required attribute for associations
  src/Field/Configurator/CommonPreConfigurator.php
  src/Resources/config/services.php
  tests/Field/Configurator/CommonPreConfiguratorTest.php
Labels: bug

#5528 Allow to use stream as upload dir for FileUploadType
  src/Field/Configurator/ImageConfigurator.php
  src/Form/Type/FileUploadType.php
Labels: feature

#5498 Fix issue 5329
  src/Field/Configurator/AssociationConfigurator.php
Labels: bug

#5533 Highlight menu items automatically based on the Request data
  src/Context/AdminContext.php
  src/Dto/MainMenuDto.php
  src/Dto/MenuItemDto.php
  src/Factory/ActionFactory.php
  src/Factory/MenuFactory.php
  src/Menu/MenuItemMatcher.php
  src/Menu/MenuItemMatcherInterface.php
  src/Resources/config/services.php
  src/Resources/views/menu.html.twig
  src/Router/AdminUrlGenerator.php
  tests/Menu/MenuItemMatcherTest.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: feature

#5538 fix #5526 #5527 #5532 by updating js style modifications to classes
  assets/js/app.js
  assets/js/field-file-upload.js
  assets/js/helpers.js
Labels: bug
