Repository EasyCorp/EasyAdminBundle, pull requests merged in 2023-06, with the labels that each got.

#5777 Compat for newer doctrine/lexer
  src/Orm/Escaper.php
Labels: bug

#5784 Fix method names in example.
  doc/fields.rst
Labels: doc

#5802 Add some Twig block to ease the extending of the header contents
  src/Resources/views/layout.html.twig
Labels: feature

#5759 Use formattedValue on code editor detail to display JSON fields
  src/Resources/views/crud/field/code_editor.html.twig
Labels: bug

#5798 Update field-text-editor.js
  assets/js/field-text-editor.js
Labels: feature

#5810 [Doc] Update docs to use the IsGranted attribute instead of the annotation
  doc/security.rst
Labels: doc
