Repository EasyCorp/EasyAdminBundle, pull requests merged in 2023-11, with the labels that each got.

#5997 Fix finding selected enum value in choices
  src/Field/Configurator/ChoiceConfigurator.php
Labels: bug

#6002 Fix incorrect '' test in form theme causing regression
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#6003 Fix the alignment of form fields in some cases
  src/Factory/FormLayoutFactory.php
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/form_theme.html.twig
  tests/Factory/FormLayoutFactoryTest.php
Labels: bug, design

#6016 Introduced new `ea.form.error` event
  assets/js/form.js
Labels: feature

#6017 fix(FileUploadType): check if is stream wrapper
  src/Form/Type/FileUploadType.php
Labels: bug

#6023 Fix country field flags in Safari browsers
  src/Resources/views/crud/field/country.html.twig
Labels: bug

#6024 Performance improvement: SecurityVoter implements supportsAttribute from CacheableVoterInterface
  src/Security/SecurityVoter.php
Labels: feature

#5959 Continue throwing same exception when edit entity
  src/Controller/AbstractCrudController.php
  src/Resources/public/app.1357e916.js
  src/Resources/public/app.1357e916.js.LICENSE.txt
  src/Resources/public/app.bb26af28.css
  src/Resources/public/app.bb26af28.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#4277 Allow multi-level submenus
  src/Context/AdminContext.php
  src/Factory/AdminContextFactory.php
  src/Factory/MenuFactory.php
  src/Factory/MenuFactoryInterface.php
Labels: feature, priority: important

#6028 Pass the original value to formatValue() method
  src/Context/AdminContext.php
  src/Factory/AdminContextFactory.php
  src/Field/Configurator/CommonPostConfigurator.php
  tests/Controller/FormFieldValueControllerTest.php
  tests/TestApplication/src/Controller/FormFieldValueController.php
Labels: bug

#6037 Update SlugField.rst
  doc/fields/SlugField.rst
Labels: doc

#6041 Add null values on NOT IN mutiple ChoiceFilter
  src/Filter/ChoiceFilter.php
Labels: bug
