Repository EasyCorp/EasyAdminBundle, pull requests merged in 2023-02, with the labels that each got.

#4988 Add support for php 8.1 enums for choice field
  src/Field/Configurator/ChoiceConfigurator.php
Labels: feature, priority: important

#5615 Init file upload field in collections
  assets/js/field-file-upload.js
Labels: bug

#5633 Fixed CSS when an entity has too many action
  assets/css/easyadmin-theme/base.scss
Labels: design

#5646 Fix: ts-wrapper style
  assets/css/easyadmin-theme/autocomplete.scss
Labels: bug, design
