Repository EasyCorp/EasyAdminBundle, pull requests merged in 2023-04, with the labels that each got.

#5703 Darker background color for readonly inputs in dark mode
  assets/css/easyadmin-theme/variables-theme.scss
Labels: design

#5717 Update dashboards.rst
  doc/dashboards.rst
Labels: bug, doc

#5718 Update the EntityPaginator interface
  src/Contracts/Orm/EntityPaginatorInterface.php
Labels: bug

#5704 hideWhenCreating() does not work with useEntryCrudForm()
  src/Factory/FieldFactory.php
Labels: bug

#5673 Fix collectionField nested prototype name
  src/Field/Configurator/CollectionConfigurator.php
Labels: bug

#5724 Fix an issue wih route parameters callable in batch and global actions
  src/Factory/ActionFactory.php
Labels: bug

#5621 Test : AbstractCrudTestCase definition to use in EasyAdmin Crud testing
  doc/index.rst
  doc/tests.rst
  src/Resources/views/crud/index.html.twig
  src/Test/AbstractCrudTestCase.php
  src/Test/Exception/InvalidClassPropertyTypeException.php
  src/Test/Exception/MissingClassMethodException.php
  src/Test/Trait/CrudTestActions.php
  src/Test/Trait/CrudTestFormAsserts.php
  src/Test/Trait/CrudTestIndexAsserts.php
  src/Test/Trait/CrudTestSelectors.php
  src/Test/Trait/CrudTestUrlGeneration.php
  tests/Controller/CategoryCrudControllerTest.php
  tests/Test/Trait/CrudTestActionsTraitTest.php
  tests/Test/Trait/CrudTestFormAssertsTraitTest.php
  tests/Test/Trait/CrudTestIndexAssertsTraitTest.php
  tests/Test/Trait/CrudTestUrlGenerationTraitTest.php
  tests/TestApplication/src/Controller/BlogPostCrudController.php
  tests/TestApplication/src/Controller/DashboardController.php
  tests/TestApplication/src/Controller/SecureDashboardController.php
Labels: feature, priority: important

#5400 Lower the impact of EA on non-admin requests
  src/DependencyInjection/CreateControllerRegistriesPass.php
  src/EventListener/AdminRouterSubscriber.php
  src/Registry/CrudControllerRegistry.php
  src/Registry/DashboardControllerRegistry.php
  src/Resources/config/services.php
  src/Twig/EasyAdminTwigExtension.php
Labels: feature
