Repository EasyCorp/EasyAdminBundle, pull requests merged in 2023-07, with the labels that each got.

#5829 Remove doubled default in variables-bootstrap.scss
  assets/css/easyadmin-theme/variables-bootstrap.scss
Labels: bug, design

#5827 Update dashboards.rst
  doc/dashboards.rst
Labels: doc

#5823 Allow searching by associated fields with the same name
  src/Orm/EntityRepository.php
  tests/Controller/Search/CustomCrudSearchControllerTest.php
  tests/TestApplication/src/Controller/Search/CustomCrudSearchController.php
  tests/TestApplication/src/DataFixtures/AppFixtures.php
  tests/TestApplication/src/Entity/BlogPost.php
Labels: bug

#5854 Fix search in JSON fields for PostgreSQL databases
  src/Field/Configurator/CommonPostConfigurator.php
  src/Orm/EntityRepository.php
Labels: bug

#5853 Priority of the getDashboardDto routeName fixed.
  src/Factory/AdminContextFactory.php
Labels: bug, status: confirmed
