Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-12, with the labels that each got.

#6599 Allow to compute action label dynamically with a callable
  doc/actions.rst
  src/Config/Action.php
  src/Dto/ActionDto.php
  src/Factory/ActionFactory.php
  tests/Config/ActionTest.php
  tests/Dto/ActionDtoTest.php
Labels: feature

#6601 Fix create form when entity id not set
  src/Dto/EntityDto.php
Labels: bug

#6617 Some fixes related to pretty URLs
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#6565 Update minimum Twig requirement to 3.15
  composer.json
Labels: feature

#6555 [FormField] Add new propertyNameSuffix to + Consistency between open & close
  src/Dto/FieldDto.php
  src/Factory/FormLayoutFactory.php
  src/Field/FieldTrait.php
  src/Field/FormField.php
  src/Form/Type/CrudFormType.php
  tests/Dto/FieldDtoTest.php
  tests/Field/FormFieldTest.php
  tests/Form/Type/CrudFormTypeFormFormFieldTest.php
Labels: feature

#6628 Update setup docs for developers not using Symfony Flex
  doc/index.rst
Labels: doc

#6627 Change the default theme to auto
  src/Dto/DashboardDto.php
Labels: feature, design

#6625 Fix menu item matcher when using pretty URLs and submenus
  src/Menu/MenuItemMatcher.php
Labels: bug

#6633 Fix menu item highlighting
  config/services.php
  src/Menu/MenuItemMatcher.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/Menu/MenuItemMatcherTest.php
  tests/PrettyUrlsTestApplication/src/Controller/DashboardController.php
Labels: bug

#6639 Fix pretty URLs when using multiple dashboards
  src/Router/AdminRouteGenerator.php
Labels: bug

#6648 Fix Fieldset collapse with new suffix.
  templates/crud/detail.html.twig
Labels: bug

#6645 Fix reference to ROUTE_LOADER_TYPE constant
  doc/dashboards.rst
Labels: doc

#6642 Add a Twig component to display flash messages
  assets/css/easyadmin-theme/base.css
  config/services.php
  public/app.fc5841f9.css
  public/entrypoints.json
  public/manifest.json
  src/Twig/Component/Alert.php
  src/Twig/Component/Option/AlertVariant.php
  templates/components/Alert.html.twig
  templates/flash_messages.html.twig
Labels: feature

#6658 Add block main_content_wrapper
  templates/layout.html.twig
Labels: feature

#6669 [Fix #6657] Correctly align icons of menu items.
  assets/css/easyadmin-theme/menu.css
Labels: bug, design

#6671 Align icon and text in a menu item
  assets/css/easyadmin-theme/menu.css
  public/app.9f3e666b.css
Labels: bug, design
