Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-09, with the labels that each got.

#6430 Drop spaceless filter in Twig templates to fix deprecation
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/new.html.twig
Labels: bug

#6414 refactor(search): Nested properties
  src/Orm/EntityRepository.php
  tests/TestApplication/src/Controller/Search/AnyTermsCrudSearchController.php
Labels: bug

#6439 Fix user menu styles when user is impersonated
  assets/css/easyadmin-theme/base.css
Labels: bug, design

#6446 Fix image overflow on detail page
  assets/css/easyadmin-theme/images.css
Labels: bug, design

#6447 Pass the entity FQCN to all action voters
  src/Controller/AbstractCrudController.php
  src/Dto/SearchDto.php
  src/Security/SecurityVoter.php
Labels: feature
