Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-10, with the labels that each got.

#6466 docs: minor syntax fixes
  doc/fields.rst
  doc/tests.rst
  src/Field/FieldTrait.php
Labels: doc

#6273 Make the "ea" global variable dynamic
  src/Context/AdminContext.php
  src/Provider/AdminContextProvider.php
  src/Twig/EasyAdminTwigExtension.php
Labels: priority: important

#6470 Improve the paginator design in responsive mode
  assets/css/easyadmin-theme/base.css
  src/Resources/public/app.90a49135.css
  src/Resources/public/app.90a49135.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/field-code-editor.d5ecf759.js
  src/Resources/public/manifest.json
  src/Resources/views/crud/paginator.html.twig
Labels: bug, design

#6471 Use attributes instead of annotations in the docs
  doc/actions.rst
  doc/dashboards.rst
  doc/fields.rst
Labels: doc

#6475 `ea` twig variable existence check fix
  src/Provider/AdminContextProvider.php
  src/Resources/views/flash_messages.html.twig
  src/Resources/views/page/login.html.twig
Labels: bug

#6480 Fix highlight text color in select autocomplete results
  assets/css/easyadmin-theme/autocomplete.css
  src/Resources/public/app.8906cebf.css
  src/Resources/public/app.8906cebf.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
Labels: bug, design

#6483 Fix modal header layout issue due to Bootstrap 5.3.3 changes
  src/Resources/views/crud/includes/_filters_modal.html.twig
Labels: bug, design

#6476 ControllerResolver::getController return value check
  src/Factory/ControllerFactory.php
Labels: bug

#6252 Admin Url Fix for linking from Edit/Detail to Index pages.
  src/Router/AdminUrlGenerator.php
Labels: bug

#6484 Fix some Twig deprecations in the form theme
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#6228 fix: check if parameters are present
  src/Controller/AbstractCrudController.php
Labels: bug

#6227 Fix empty query term conditions
  src/Orm/EntityRepository.php
  tests/Controller/Search/IdTermCrudSearchControllerTest.php
  tests/TestApplication/src/Controller/Search/IdTermCrudSearchController.php
Labels: bug

#6485 Allow to set HTML attributes in fields on index and detail pages, not only on form pages
  doc/fields.rst
  src/Dto/FieldDto.php
  src/Field/FieldTrait.php
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/index.html.twig
  tests/Controller/CustomFieldAttributeControllerTest.php
  tests/TestApplication/src/Controller/CustomFieldAttributeCrudController.php
Labels: feature

#6311 Update CollectionField.rst file for better documentation (adding extra considerations for its implementation)
  doc/fields/CollectionField.rst
Labels: doc

#6487 Allow to customize the string representation of Collection field entries
  doc/fields/CollectionField.rst
  src/Field/CollectionField.php
  src/Resources/views/crud/form_theme.html.twig
  src/Twig/EasyAdminTwigExtension.php
  tests/Twig/EasyAdminTwigExtensionTest.php
Labels: feature

#6212 Prevent a crash when loading filters
  src/Field/Configurator/AssociationConfigurator.php
Labels: bug

#6494 Fix ImageField design in dark mode
  assets/css/easyadmin-theme/forms.css
Labels: bug, design
