Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-02, with the labels that each got.

#6126 Don't translate form values that are already translated
  src/Field/Configurator/CurrencyConfigurator.php
  src/Field/Configurator/LanguageConfigurator.php
  src/Field/Configurator/LocaleConfigurator.php
  src/Field/Configurator/TimezoneConfigurator.php
Labels: bug

#6137 Add Expression Language as a dependency
  composer.json
  src/Orm/Escaper.php
Labels: bug

#6138 Revert the last Pull Request
  .ddev/example/Controller/Admin/DashboardController.php
  composer.json
Labels: bug

#6140 Add Doctrine ORM 3.x compatibility
  composer.json
  src/Dto/EntityDto.php
  src/Factory/EntityFactory.php
  src/Factory/FieldFactory.php
  src/Factory/FilterFactory.php
  src/Filter/Configurator/TextConfigurator.php
  src/Orm/EntityRepository.php
  src/Orm/Escaper.php
  src/Provider/FieldProvider.php
  tests/Field/Configurator/ChoiceConfiguratorTest.php
  tests/TestApplication/src/DataFixtures/AppFixtures.php
  tests/TestApplication/src/Entity/BlogPost.php
Labels: feature

#6149 Update NumericFilter.php for fix STORED_AS_CENTS if not stored as cents
  src/Filter/NumericFilter.php
Labels: bug

#6165 [Doc] Add required version to use Expressions
  doc/security.rst
Labels: doc

#6155 fix: incorrect display of html attributes on detail page
  src/Resources/views/crud/detail.html.twig
Labels: bug

#6168 Add ability to clone fields
  src/Contracts/Field/FieldInterface.php
  src/Field/FieldTrait.php
Labels: feature

#6153 Update filters.rst
  doc/filters.rst
Labels: bug, doc

#6164 Fix ajax editing of fields with invalid permission
  src/Controller/AbstractCrudController.php
  tests/Controller/CategoryCrudControllerTest.php
  tests/TestApplication/src/Controller/CategoryCrudController.php
  tests/TestApplication/src/Entity/Category.php
Labels: bug
