Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-08, with the labels that each got.

#6397 Fix selection of menu items after Dashboard menu item
  src/Menu/MenuItemMatcher.php
  tests/Menu/MenuItemMatcherTest.php
Labels: bug

#6398 DDEV enhancements
  .ddev/commands/web/run-tests
  .ddev/commands/web/setup
  .ddev/config.yaml
  .ddev/docker-compose.web.yaml
  README.md
Labels: feature

#6400 Pass the date/time predefine formats as is to IntlFormatter
  src/Config/Crud.php
  src/Field/DateTimeField.php
  tests/Config/CrudTest.php
Labels: bug

#6413 Revert filter modal scrollable
  src/Resources/views/crud/includes/_filters_modal.html.twig
Labels: bug, design

#6418 Fix background color of Trix editor link input in dark theme
  assets/css/form-type-text-editor.css
Labels: bug, design
