Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-11, with the labels that each got.

#6495 Fix the highlighter so that it doesn't crash on REGEX symbols anymore
  assets/js/app.js
Labels: bug

#6496 Fix next page url
  src/Orm/EntityPaginator.php
Labels: bug

#6500 Fix the priority/order of the generated routes
  src/Router/AdminRouteGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
Labels: bug

#6502 Fix version where pretty admin URLs were added
  doc/dashboards.rst
  src/Router/AdminUrlGenerator.php
  tests/baseline-ignore.txt
Labels: bug

#6504 Allow `AdminCrud` and `AdminAction` attributes to be used without parameter names
  src/Router/AdminRouteGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/PrettyUrlsTestApplication/src/Controller/UserCrudController.php
Labels: feature

#6507 Improve the detection of pretty URLs usage
  src/Context/AdminContext.php
  src/Factory/AdminContextFactory.php
  src/Resources/config/services.php
  src/Router/AdminRouteGenerator.php
Labels: bug

#6515 Fix performance issue when using pretty URLs
  src/EventListener/AdminRouterSubscriber.php
  src/Resources/config/services.php
  src/Router/AdminRouteGenerator.php
Labels: bug

#6520 Fix filters when using pretty URLs
  src/Factory/FormFactory.php
  src/Field/Configurator/BooleanConfigurator.php
  src/Router/AdminRouteGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
Labels: bug

#6522 Fix an issue when generating pretty URLs for the dashboard
  src/Router/AdminUrlGenerator.php
Labels: bug

#6512 fix: before entity deleted event cannot be stopped in batch delete
  src/Controller/AbstractCrudController.php
Labels: feature

#6526 Fix the design of errored form fields
  assets/css/easyadmin-theme/forms.css
  assets/css/easyadmin-theme/variables-theme.css
  src/Resources/public/app.d52c6a33.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
  src/Resources/views/crud/form_theme.html.twig
Labels: bug, design

#6539 Trim trailing slash from pretty index route path
  src/Router/AdminRouteGenerator.php
Labels: bug

#6543 Bump PHP requirements to PHP 8.1
  .github/workflows/ci.yaml
  composer.json
Labels: feature

#6528 Correctly extract the entityID for the title when using pretty URLs
  src/Factory/AdminContextFactory.php
Labels: bug

#6536 Split `ea_form_fieldset_open_row` form theme block
  config/services.php
  src/Twig/FormExtension.php
  templates/crud/form_theme.html.twig
Labels: feature

#6563 use image_uri for the lightbox thumbnail
  templates/crud/form_theme.html.twig
Labels: bug

#6567 Fix an edge-case when using pretty URLs
  src/Router/AdminUrlGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: bug

#6572 [Twig/Icon] Fix typo in user icon name `inernal` => `internal`
  templates/layout.html.twig
Labels: bug

#6568 Fix menu item matcher when using pretty URLs
  src/Menu/MenuItemMatcher.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
Labels: bug, status: confirmed

#6573 Replace `sr-only` class with `visually-hidden`
  templates/crud/index.html.twig
Labels: bug, design

#6571 Fix icon sets in documentation
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/fields.rst
Labels: bug, doc

#6583 Fix some CSS styles
  assets/css/easyadmin-theme/base.css
  assets/css/easyadmin-theme/datagrids.css
Labels: bug, design

#6589 Fix icons set name
  templates/crud/form_theme.html.twig
Labels: bug

#6570 Use buildDir for cache
  config/services.php
  src/Cache/CacheWarmer.php
  src/DependencyInjection/CreateControllerRegistriesPass.php
  src/Factory/AdminContextFactory.php
  src/Registry/DashboardControllerRegistry.php
Labels: feature

#6574 Use kekab-case instead of snake_case for Pretty URL route paths.
  doc/crud.rst
  src/Router/AdminRouteGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
Labels: feature

#6597 Fix batch_delete paths on docs
  doc/crud.rst
Labels: doc

#6594 Fix reset filter link
  templates/crud/index.html.twig
Labels: bug, status: confirmed

#6596 fix(AbstractDashboard): fix defaults icons in AbstractDashboard
  assets/icons/internal/user-lock.svg
  src/Controller/AbstractDashboardController.php
Labels: bug

#6604 Allow use of ux-icons in form fields
  src/Field/FormField.php
Labels: bug
