Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-07, with the labels that each got.

#6330 [PATCH] Erroneously fails to search when table names match
  src/Orm/EntityRepository.php
Labels: bug

#6355 Fix assets not loaded for fields generated automatically
  src/Collection/EntityCollection.php
  src/Controller/AbstractCrudController.php
  src/Orm/EntityRepository.php
Labels: bug

#6350 Update actions.rst (fix batchActionEntityIds)
  doc/actions.rst
Labels: doc

#6347 Pass added element in ea.collection.item-added event
  assets/js/field-collection.js
Labels: feature

#6296 Render expanded invalid collection entry
  src/Resources/views/crud/form_theme.html.twig
Labels: feature

#6364 fix form_theme.html.twig error
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#6362 Fix the height of empty cells in datagrids on small devices
  assets/css/easyadmin-theme/datagrids.css
  src/Resources/public/app.19616e33.css
  src/Resources/public/app.19616e33.rtl.css
  src/Resources/public/entrypoints.json
  src/Resources/public/manifest.json
Labels: bug, design

#6368 fix #6363 Use the default domain when translating a page title.
  src/Dto/CrudDto.php
  src/Resources/views/crud/detail.html.twig
  src/Resources/views/crud/edit.html.twig
  src/Resources/views/crud/index.html.twig
  src/Resources/views/crud/new.html.twig
Labels: bug

#6371 Fix percent format
  src/Field/Configurator/NumberConfigurator.php
  src/Field/Configurator/PercentConfigurator.php
  src/Resources/config/services.php
  tests/Field/PercentFieldTest.php
Labels: bug

#6372 Fix twig regex for collection field (related to #6364)
  src/Resources/views/crud/form_theme.html.twig
Labels: bug

#6377 Make filter modal scrollable
  src/Resources/views/crud/includes/_filters_modal.html.twig
Labels: feature, design

#6383 Update the logic of the menu item matcher
  UPGRADE.md
  src/Contracts/Menu/MenuItemMatcherInterface.php
  src/Factory/MenuFactory.php
  src/Menu/MenuItemMatcher.php
  src/Resources/config/services.php
  tests/Menu/MenuItemMatcherTest.php
Labels: bug

#6388 Update EntityRepository.php
  src/Orm/EntityRepository.php
Labels: bug

#6390 Fix flag sizes in the country field in Safari browsers
  src/Field/Configurator/CountryConfigurator.php
  tests/Field/CountryFieldTest.php
Labels: bug, design

#6395 Locale fix
  src/Factory/AdminContextFactory.php
  src/Router/AdminUrlGenerator.php
Labels: bug
