Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-04, with the labels that each got.

#6242 Fixed invalid DQL
  src/Orm/EntityRepository.php
Labels: bug

#6240 Fixed warning in DateTimeFilterType.php
  src/Form/Filter/Type/DateTimeFilterType.php
Labels: bug

#6237 Fix login form bottom padding
  src/Resources/views/page/login.html.twig
Labels: design

#6238 Fix vertical scrollbar
  assets/css/easyadmin-theme/base.css
Labels: bug, design

#6250 Allow fields containing null-safe property paths
  src/Form/Type/CrudFormType.php
Labels: feature

#6216 fix: If it's a JoinColumnMapping, use property access
  src/Field/Configurator/CommonPreConfigurator.php
  src/Filter/Configurator/EntityConfigurator.php
Labels: bug

#6267 Add a note about possible XSS attacks
  doc/crud.rst
Labels: doc

#6270 Change the default title of detail page to avoid XSS issues
  UPGRADE.md
  doc/crud.rst
  src/Resources/translations/EasyAdminBundle.ar.php
  src/Resources/translations/EasyAdminBundle.bg.php
  src/Resources/translations/EasyAdminBundle.ca.php
  src/Resources/translations/EasyAdminBundle.cs.php
  src/Resources/translations/EasyAdminBundle.da.php
  src/Resources/translations/EasyAdminBundle.de.php
  src/Resources/translations/EasyAdminBundle.el.php
  src/Resources/translations/EasyAdminBundle.en.php
  src/Resources/translations/EasyAdminBundle.es.php
  src/Resources/translations/EasyAdminBundle.eu.php
  src/Resources/translations/EasyAdminBundle.fa.php
  src/Resources/translations/EasyAdminBundle.fi.php
  src/Resources/translations/EasyAdminBundle.fr.php
  src/Resources/translations/EasyAdminBundle.gl.php
  src/Resources/translations/EasyAdminBundle.he.php
  src/Resources/translations/EasyAdminBundle.hr.php
  src/Resources/translations/EasyAdminBundle.hu.php
  src/Resources/translations/EasyAdminBundle.hy.php
  src/Resources/translations/EasyAdminBundle.id.php
  src/Resources/translations/EasyAdminBundle.it.php
  src/Resources/translations/EasyAdminBundle.lb.php
  src/Resources/translations/EasyAdminBundle.lt.php
  src/Resources/translations/EasyAdminBundle.mk.php
  src/Resources/translations/EasyAdminBundle.nl.php
  src/Resources/translations/EasyAdminBundle.no.php
  src/Resources/translations/EasyAdminBundle.pl.php
  src/Resources/translations/EasyAdminBundle.pt.php
  src/Resources/translations/EasyAdminBundle.pt_BR.php
  src/Resources/translations/EasyAdminBundle.ro.php
  src/Resources/translations/EasyAdminBundle.ru.php
  src/Resources/translations/EasyAdminBundle.sk.php
  src/Resources/translations/EasyAdminBundle.sl.php
  src/Resources/translations/EasyAdminBundle.sr_RS.php
  src/Resources/translations/EasyAdminBundle.sv.php
  src/Resources/translations/EasyAdminBundle.tr.php
  src/Resources/translations/EasyAdminBundle.uk.php
  src/Resources/translations/EasyAdminBundle.zh_CN.php
Labels: bug
