Repository EasyCorp/EasyAdminBundle, pull requests merged in 2024-05, with the labels that each got.

#6292 Fix search engine for PostgreSQL databases when querying numbers
  src/Orm/EntityRepository.php
Labels: bug

#6288 Fix top border
  assets/css/easyadmin-theme/base.css
Labels: bug, design

#6258 [ImageField] Support constraint validation
  doc/fields/ImageField.rst
  src/Field/Configurator/ImageConfigurator.php
  src/Field/ImageField.php
  src/Form/Type/FileUploadType.php
Labels: feature

#6282 feat: allow slug field to be triggered by select fields also
  assets/js/field-slug.js
Labels: bug
