Repository EasyCorp/EasyAdminBundle, pull requests merged in 2025-01, with the labels that each got.

#6661 Fix for issue #6519 (Pretty URLs in tests)
  .ddev/example/Controller/Admin/DashboardController.php
  src/Router/AdminUrlGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
Labels: bug

#6677 Fix the color of the border of item remove icon in autocomplete lists
  assets/css/easyadmin-theme/autocomplete.css
  public/app.15c1f5f4.css
  public/entrypoints.json
  public/manifest.json
Labels: bug, design

#6679 Fix allignment and size of menu items
  assets/css/easyadmin-theme/menu.css
Labels: bug, design

#6650 Added documentation on JavaScript events
  doc/events.rst
  doc/fields/CollectionField.rst
Labels: doc

#6683 [Doc] Minor update in the security chapter
  doc/security.rst
Labels: doc

#6649 Add a new Twig component to create Action Menus
  assets/css/easyadmin-theme/base.css
  assets/css/easyadmin-theme/datagrids.css
  assets/icons/internal/dots-horizontal.svg
  composer.json
  public/app.62f32d02.css
  public/entrypoints.json
  public/manifest.json
  src/DependencyInjection/EasyAdminExtension.php
  templates/components/ActionMenu.html.twig
  templates/components/ActionMenu/ActionList.html.twig
  templates/components/ActionMenu/ActionList/Content.html.twig
  templates/components/ActionMenu/ActionList/Divider.html.twig
  templates/components/ActionMenu/ActionList/Header.html.twig
  templates/components/ActionMenu/ActionList/Item.html.twig
  templates/components/ActionMenu/Button.html.twig
  templates/components/ActionMenu/Overlay.html.twig
  templates/crud/index.html.twig
  templates/layout.html.twig
  tests/PrettyUrlsTestApplication/src/Kernel.php
  tests/TestApplication/src/Kernel.php
Labels: feature

#6612 doc: add explanation of custom action
  doc/actions.rst
Labels: doc

#6634 fixes #6554: Removing fix for pretty url filters as it breaks render…
  src/Field/Configurator/BooleanConfigurator.php
Labels: bug

#6684 Deprecate the AdminContext:getReferrer() method
  UPGRADE.md
  src/Context/AdminContext.php
Labels: bug

#6688 Fix pretty URLs with i18n backends
  templates/layout.html.twig
Labels: bug

#6696 Fix an edge-case about pretty URLs and cache warm up
  config/services.php
  src/EventListener/AdminRouterSubscriber.php
  src/Router/AdminRouteGenerator.php
Labels: bug

#6697 Fix asset preloading
  templates/includes/_css_assets.html.twig
  templates/includes/_js_assets.html.twig
Labels: bug

#6700 Add tests for web assets
  composer.json
  templates/includes/_css_assets.html.twig
  templates/includes/_js_assets.html.twig
  tests/Controller/AssetsControllerTest.php
  tests/TestApplication/src/Controller/AssetsController.php
Labels: bug

#6702 When using pretty URLs, redirect ugly URLs automatically
  config/services.php
  src/EventListener/AdminRouterSubscriber.php
  src/Router/AdminRouteGenerator.php
  src/Router/AdminRouteLoader.php
  templates/layout.html.twig
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/bootstrap.php
Labels: bug, feature

#6705 Update MenuItemMatcher.php, fix menu active status
  src/Menu/MenuItemMatcher.php
Labels: bug

#6709 Update AdminRouterSubscriber.php
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#6716 Allow customizing some bits of the login form page via twig blocks
  templates/page/login.html.twig
Labels: feature, design

#6714 Added some missing deprecations related to referrer URLs
  UPGRADE.md
  doc/actions.rst
  src/ArgumentResolver/BatchActionDtoResolver.php
  src/Contracts/Context/AdminContextInterface.php
  src/Dto/BatchActionDto.php
  src/Factory/ActionFactory.php
  src/Provider/AdminContextProvider.php
  src/Router/AdminUrlGenerator.php
  src/Router/AdminUrlGeneratorInterface.php
  tests/Context/AdminContextTest.php
  tests/Controller/CategoryCrudControllerTest.php
Labels: bug

#6717 Do not redirect to pretty url when crud controller is null
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#6724 Force auto-generated CSRF token id
  src/Factory/FormFactory.php
Labels: bug

#6721 Fix set current route parameters with pretty urls enabled
  src/Router/AdminUrlGenerator.php
Labels: bug

#6734 Fix Dashboard menu item highlighting
  config/services.php
  src/Menu/MenuItemMatcher.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/Menu/MenuItemMatcherTest.php
Labels: bug

#6720 Allow customize entity row attributes on index page
  templates/crud/index.html.twig
Labels: feature

#6738 Fix batch actions with ugly URLs
  src/ArgumentResolver/BatchActionDtoResolver.php
Labels: bug

#6742 Inject interfaces in menu item matcher instead of concrete implementations.
  src/Menu/MenuItemMatcher.php
Labels: bug

#6741 Improve the URL Field and add tests
  src/Field/Configurator/UrlConfigurator.php
  src/Field/UrlField.php
  tests/Field/AbstractFieldTest.php
  tests/Field/UrlFieldTest.php
Labels: bug

#6745 Keep URL absolute type for dashboards URLs
  Makefile
  src/Router/AdminUrlGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/Router/AdminUrlGeneratorTest.php
Labels: bug

#6748 Make NullFilter::CHOICE_VALUE_* consts public
  src/Filter/NullFilter.php
Labels: feature

#6749 Provide $previous exception context for EntityRemoveException
  src/Controller/AbstractCrudController.php
  src/Exception/BaseException.php
  src/Exception/EntityRemoveException.php
Labels: feature

#6740 Bug #5161 Disallow clear in AssociationField when field is required
  src/Field/Configurator/CommonPreConfigurator.php
Labels: bug

#6760 Fix an edge-cse with pretty URLs and multiple dashboards
  src/Router/AdminUrlGenerator.php
Labels: bug

#6773 Fix typo
  doc/actions.rst
Labels: doc

#6769 Update admin dashboard
  doc/actions.rst
  doc/crud.rst
  doc/dashboards.rst
  doc/design.rst
  doc/security.rst
  src/Attribute/AdminDashboard.php
  src/Resources/skeleton/dashboard.tpl
  src/Router/AdminRouteGenerator.php
  tests/Controller/PrettyUrls/PrettyUrlsControllerTest.php
  tests/PrettyUrlsTestApplication/src/Controller/ThirdDashboardController.php
Labels: feature
