Repository EasyCorp/EasyAdminBundle, pull requests merged in 2025-06, with the labels that each got.

#6969 Add some Generics
  .ddev/example/Controller/Admin/BlogArticleCrudController.php
  .ddev/example/Controller/Admin/CategoryCrudController.php
  doc/dashboards.rst
  src/Contracts/Controller/CrudControllerInterface.php
  src/Contracts/Event/EntityLifecycleEventInterface.php
  src/Controller/AbstractCrudController.php
  src/Dto/EntityDto.php
  src/Event/AbstractLifecycleEvent.php
  src/Security/SecurityVoter.php
  tests/PrettyUrlsTestApplication/src/Controller/BlogPostCrudController.php
  tests/PrettyUrlsTestApplication/src/Controller/CategoryCrudController.php
  tests/PrettyUrlsTestApplication/src/Controller/UserCrudController.php
  tests/TestApplication/src/Controller/ActionsCrudController.php
  tests/TestApplication/src/Controller/AssetsController.php
  tests/TestApplication/src/Controller/BlogPostCrudController.php
  tests/TestApplication/src/Controller/CategoryCrudController.php
  tests/TestApplication/src/Controller/CustomFieldAttributeCrudController.php
  tests/TestApplication/src/Controller/ErrorFieldDoesNotBelongToAnyTabCrudController.php
  tests/TestApplication/src/Controller/FormFieldHelpController.php
  tests/TestApplication/src/Controller/FormFieldLabelController.php
  tests/TestApplication/src/Controller/FormFieldValueController.php
  tests/TestApplication/src/Controller/FormFieldsetsCrudController.php
  tests/TestApplication/src/Controller/Search/AnyTermsCrudSearchController.php
  tests/TestApplication/src/Controller/Search/CustomCrudSearchController.php
  tests/TestApplication/src/Controller/Search/DefaultCrudSearchController.php
  tests/TestApplication/src/Controller/Search/IdTermCrudSearchController.php
  tests/TestApplication/src/Controller/Sort/BillCrudController.php
  tests/TestApplication/src/Controller/Sort/CustomerCrudController.php
  tests/TestApplication/src/Controller/Sort/PageCrudController.php
  tests/TestApplication/src/Controller/Sort/WebsiteCrudController.php
Labels: feature

#6974 Fix trailing spaces in docs
  README.md
  doc/tests.rst
Labels: doc, codex

#6975 Fix typo in tests doc
  doc/tests.rst
Labels: doc, codex

#6976 Docs cleanup
  doc/dashboards.rst
  doc/events.rst
  doc/security.rst
Labels: doc, codex

#6977 Update docs and comments
  doc/fields/CountryField.rst
  src/Factory/FieldFactory.php
  src/Form/Type/EaFormColumnType.php
  src/Form/Type/EaFormFieldsetType.php
  src/Form/Type/EaFormPanelType.php
  src/Form/Type/EaFormRowType.php
  src/Form/Type/EasyAdminGroupType.php
Labels: doc, codex

#6980 Fix fileSize() method in Twig extension
  src/Twig/EasyAdminTwigExtension.php
  tests/Twig/EasyAdminTwigExtensionTest.php
Labels: codex

#6981 CrudControllerInterface: add missing EntityDto generics
  src/Contracts/Controller/CrudControllerInterface.php
Labels: feature

#6983 Add typing for PHPStan level 6
  src/Field/Configurator/CollectionConfigurator.php
  src/Field/Configurator/CommonPostConfigurator.php
  src/Field/FieldTrait.php
  src/Field/FormField.php
  src/Filter/ArrayFilter.php
  src/Filter/BooleanFilter.php
  src/Filter/ChoiceFilter.php
  src/Filter/ComparisonFilter.php
  src/Filter/DateTimeFilter.php
  src/Filter/EntityFilter.php
  src/Filter/FilterTrait.php
  src/Filter/NullFilter.php
  src/Filter/NumericFilter.php
  src/Filter/TextFilter.php
  src/Form/DataTransformer/StringToFileTransformer.php
  src/Form/EventListener/CrudAutocompleteSubscriber.php
  src/Form/EventListener/FormLayoutSubscriber.php
  src/Form/Type/Model/FileUploadState.php
  src/Inspector/DataCollector.php
Labels: feature

#6992 Add phpdoc for some arrays
  src/Attribute/AdminDashboard.php
  src/Command/MakeCrudControllerCommand.php
  src/Config/Action.php
  src/Config/Crud.php
  src/Config/KeyValueStore.php
  src/Config/Menu/CrudMenuItem.php
  src/Config/Menu/MenuItemTrait.php
  src/Contracts/Field/FieldTraitAwareInterface.php
  src/Dto/ActionDto.php
  src/Dto/CrudDto.php
  src/Dto/EntityDto.php
  src/Dto/FieldDto.php
  src/Dto/FilterConfigDto.php
  src/Dto/FilterDto.php
  src/Dto/MenuItemDto.php
  src/Field/FieldTrait.php
  src/Filter/FilterTrait.php
  src/Form/Filter/Type/ComparisonFilterType.php
  src/Form/Filter/Type/NumericFilterType.php
  src/Provider/FieldProvider.php
  src/Registry/TemplateRegistry.php
  src/Router/AdminUrlGenerator.php
  src/Router/AdminUrlGeneratorInterface.php
  src/Translation/TranslatableMessageBuilder.php
  src/Twig/EasyAdminTwigExtension.php
Labels: feature

#6990 Deprecate the global ea variable in favor of a Twig function
  UPGRADE.md
  src/Contracts/Provider/AdminContextProviderInterface.php
  src/Provider/AdminContextProvider.php
  src/Twig/EasyAdminTwigExtension.php
  templates/crud/detail.html.twig
  templates/crud/edit.html.twig
  templates/crud/field/array.html.twig
  templates/crud/field/boolean.html.twig
  templates/crud/field/code_editor.html.twig
  templates/crud/field/text.html.twig
  templates/crud/field/text_editor.html.twig
  templates/crud/field/textarea.html.twig
  templates/crud/field/url.html.twig
  templates/crud/filters.html.twig
  templates/crud/form_theme.html.twig
  templates/crud/index.html.twig
  templates/crud/new.html.twig
  templates/crud/paginator.html.twig
  templates/flash_messages.html.twig
  templates/label/null.html.twig
  templates/layout.html.twig
  templates/menu.html.twig
  templates/page/content.html.twig
  templates/page/login.html.twig
Labels: codex
