Repository EasyCorp/EasyAdminBundle, pull requests merged in 2025-09, with the labels that each got.

#7063 [Doc] Update the doc index page
  doc/index.rst
Labels: doc

#7074 Simplified the new AdminRoute attribute
  doc/actions.rst
  doc/crud.rst
  src/Attribute/AdminRoute.php
  src/Router/AdminRouteGenerator.php
  tests/AdminRouteTestApplication/src/Controller/FooController.php
  tests/AdminRouteTestApplication/src/Controller/InvokableController.php
  tests/AdminRouteTestApplication/src/Controller/ReportsController.php
  tests/AdminRouteTestApplication/src/Controller/StandaloneMethodsController.php
Labels: feature

#7076 [Doc] Update the docs about integrating Symfony controllers in the backend
  doc/actions.rst
Labels: doc

#7085 Update filters.rst (DatetimeFilter -> DateTimeFilter)
  doc/filters.rst
Labels: doc

#7093 Do not use deprecated `ea` in macros.
  templates/crud/detail.html.twig
Labels: bug

#7095 Fix generating locale change URLs for custom route
  templates/layout.html.twig
Labels: bug

#7094 Update the default ordering of actions
  assets/css/easyadmin-theme/base.css
  assets/css/easyadmin-theme/datagrids.css
  assets/css/easyadmin-theme/variables-theme.css
  assets/icons/internal/blank.svg
  doc/actions.rst
  public/app.65292ccb.css
  public/entrypoints.json
  public/manifest.json
  src/Config/Actions.php
  src/Dto/ActionConfigDto.php
  src/Factory/ActionFactory.php
  templates/components/ActionMenu/ActionList/Item.html.twig
  templates/crud/detail.html.twig
  templates/crud/edit.html.twig
  templates/crud/index.html.twig
  templates/crud/new.html.twig
  tests/Controller/ActionsCrudControllerTest.php
  tests/Controller/CustomActionOrderTest.php
  tests/Controller/DefaultActionOrderTest.php
  tests/Factory/ActionFactoryTest.php
  tests/TestApplication/src/Controller/BlogPostCrudController.php
  tests/TestApplication/src/Controller/CustomActionOrderCrudController.php
Labels: feature
