Repository EasyCorp/EasyAdminBundle, pull requests merged in 2025-02, with the labels that each got.

#6764 fix custom action not working when url has a search query
  templates/layout.html.twig
Labels: bug

#6771 Fix/6598 pretty urls and selected menu item
  .ddev/commands/web/run-tests
  .ddev/commands/web/setup
  .ddev/config.yaml
  .ddev/example/Controller/Admin/BlogArticleCrudController.php
  .ddev/example/Controller/Admin/CategoryCrudController.php
  .ddev/example/Controller/Admin/DashboardController.php
  .ddev/example/config/routes/easyadmin.yaml
  src/Menu/MenuItemMatcher.php
Labels: bug

#6754 Add default locale to all pretty routes
  config/services.php
  src/Router/AdminRouteGenerator.php
  tests/Router/AdminRouteGeneratorTest.php
Labels: bug

#6797 docs: fixes typos in fields.rst
  doc/fields.rst
Labels: doc

#6798 wrap form tab html attr in double quotes
  templates/crud/form_theme.html.twig
Labels: bug

#6801 [Doc] Clarify that AdminDashboard only works for pretty URLs
  doc/dashboards.rst
Labels: doc

#6806 Change AdminRouterSubscriber::getSymfonyControllerFqcn so it generates relative paths
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#6823 chore(doc): fix typo route attribute
  doc/dashboards.rst
Labels: doc

#6827 Remove prefix from URL to match in AdminRouterSubscriber::getSymfonyControllerFqcn
  src/EventListener/AdminRouterSubscriber.php
Labels: bug

#6832 Always return to index when using SAVE_AND_RETURN button
  src/Controller/AbstractCrudController.php
Labels: bug

#6829 Fix typo
  doc/dashboards.rst
Labels: doc

#6831 Display as form for actions
  assets/css/easyadmin-theme/base.css
  src/Config/Action.php
  src/Dto/ActionDto.php
  templates/crud/action.html.twig
  tests/Controller/ActionsCrudControllerTest.php
  tests/TestApplication/src/Controller/ActionsCrudController.php
Labels: feature
