Repository EasyCorp/EasyAdminBundle, pull requests merged in 2025-04, with the labels that each got.

#6899 Error message div should not inherit widget attr.class CSS classes
  templates/crud/form_theme.html.twig
Labels: bug

#6890 min php is 8.1
  doc/index.rst
Labels: doc

#6765 Allow for custom routes to use EasyAdmin's context, especially in templates
  src/EventListener/AdminRouterSubscriber.php
Labels: feature

#6902 Fix double encoded urls
  src/Factory/ControllerFactory.php
Labels: bug
